### ISSUE TITLE
Azure security engineer expert certification

### ISSUE THREAD

**Issue by nzahrani-GitHub** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#104]
There is a huge demand for:

-  Azure security engineer expert skillsets
-  Azure security architect expert skillsets

How to reach Microsoft to propose creating the above two Azure security expert-level certifications?

**Comment by R-C-Stewart** [comment]
We have taken this information into our system for consideration.  We have been thinking about each of these items previously, so this gives us a couple more proof points on that need.  There is no specific plan at this point, but it is being discussed.

**Comment by polichtm** [comment]
@nzahrani-GitHub 
pls let us know if have any questions regarding the labs
rgds
Marcin
