### ISSUE TITLE
AZ-500T00A-ENU-TrainerHandbook

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#105]
Hello 😀

I have an issue the TrainerHandbook VS the slides
The slides are not updated on the book
Thanks

**Comment by R-C-Stewart** [comment]
We are going to refresh the content on the Trainer Handbook by the end of the month.

**Comment by polichtm** [comment]
@chrzanowskiItta 
pls let us know if there are any additional requests concerning this
rgds
Marcin
