### ISSUE TITLE
Firewall IP entry not specified in lab instructions

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#106]
# Module: 3
#### Step: 2

Description of issue
The lab is not clear that the public address needs to be added into the firewall rule. If we follow the instructions it informs us that we need to create a firewall rule without a start and end IP address. Can you please indicate which IP address to enter for the start IP and end IP in the rule.
![AZ500-Mod10-issue](https://user-images.githubusercontent.com/18732050/104541218-da11fa00-566c-11eb-8161-cfdb1e6b46de.PNG)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Bren
updated
rgds
Marcin
