### ISSUE TITLE
External IP pending in lab 9 task 7 step 7

### ISSUE THREAD

**Issue by John-bit-87** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#108]
# Lab: 09
### Step: 7

The external IP stays pending. Is this supposed to happen? Are we supposed to use the internal IP instead?

**Comment by polichtm** [comment]
Hi John,
this should be a private IP address.
Have you followed up with your instructor?
rgds
Marcin

**Comment by John-bit-87** [comment]
Hello Marcin,

Yes, however, it was still a bit unclear as the external IP address column stays pending and the instructions stated to use the external IP address. Using the IP address in the internal IP column in the curl statement worked for us.

Thank you
John

**Comment by polichtm** [comment]
Hi John,
appreciate the clarification. We'll update the instructions to eliminate any ambiguity
rgds
Marcin

**Comment by John-bit-87** [comment]
Hello Marcin,

No problem at all.

Thank you
John Jimenez

**Comment by polichtm** [comment]
updated
rgds
Marcin
