### ISSUE TITLE
Lab 13 Task 4 Steps 4-8

### ISSUE THREAD

**Issue by John-bit-87** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#109]
#### Step: 4-8

The steps no longer match what is in Azure. You now have to go to Agents Configuration on the left menu of your workspace and select the appropriate data option.

![image](https://user-images.githubusercontent.com/37407681/109425777-0df47500-79b8-11eb-86a3-3481a1f09154.png)

**Comment by polichtm** [comment]
updated
rgds
Marcin
