### ISSUE TITLE
can't access to myPublicVm

### ISSUE THREAD

**Issue by brahmiam** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#111]
# Module: AZ500
#### Step: 9

Description of issue

For the creation of myVmPublic, you specify : Public inbound ports : None

So there is no way to RDP into it at a later stage.

either let the default option or create an appropriate nsg

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Medhi,
would you mind clarifying which specific exercise, task, and step the phrase "a later stage" refers to ?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
rgds
Marcin
