### ISSUE TITLE
One radio button selection missing from PIM task

### ISSUE THREAD

**Issue by mmaraa** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#112]
# Module: 01
#### Step: 07

By default, Assignment type is eligible. --> Review the Assignment type and select **Active** as an assignment type and click Assign. 

Add also a justification for an active assignment.

![image](https://user-images.githubusercontent.com/10687492/111084871-44d09c00-851d-11eb-9826-021a9f04b9e8.png)
 Or do you mean to give a permanten eligible role in this step?

**Comment by polichtm** [comment]
Hi Markus,
the latter. Pls refer to Exercise 2 task 2:

On the My roles | Azure AD roles blade, locate the Security Administrator role, and click Activate.

Click the warning Additional verification required. Click to continue.

Follow the instructions to verify your identity.

Note: You only have to authenticate once per session.

Once you are back in the Azure Portal interface, on the Activate - Security Administrator blade, in the Reason text box, type a text providing justification for the activation, and then click Activate.

Note: The auto approval process should complete.

Back on the My roles | Azure AD roles blade, click the Active assignments tab and notice that the listing of active assignments includes Security Administrator but not the Global Reader role.

rgds
Marcin
