### ISSUE TITLE
Lab 4 Ex 2 Task 4 Step 5 Premium checkbox not seen

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#115]
I'm at Lab 04 MFA, Conditional Access and AAD Identity Protection
Exercise 2: Implement Azure MFA
Task 4: Assign Azure AD Premium P2 licenses to Azure AD users
Step 5.  
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/master/Instructions/Labs/LAB_04_MFAConditionalAccessandAADIdentityProtection.md

The instructions says "select the Azure Active Directory Premium P2 checkbox, and click + Assign.
But I don't see that in the blade.
![Screen Shot 2021-03-25 at 4 07 19 AM](https://user-images.githubusercontent.com/300046/112455781-a663e800-8d1f-11eb-9509-b1a25f71b77b.png)

**Comment by polichtm** [comment]
Hi Wilson, 
you have to activate the trial first (in task 2)

#### Task 2: Activate Azure AD Premium P2 trial

In this task, you will sign up for the Azure AD Premium P2 free trial. 

1. In the Azure portal, in the toolbar, click the **Directory + subscription** icon, located to the right of the Cloud Shell icon. 

1. In the **Directory + subscription** blade, click the newly created tenant, **AdatumLab500-04**.

    >**Note**: You may need to refresh the browser window if the **AdatumLab500-04** entry does not appear in the **Directory + subscription** filter list.

1. On the **AdatumLab500-04** blade, in the **Manage** section, click **Licenses**.

1. On the **Licenses \| Overview** blade, in the **Manage** section, click **All products** and then click **+ Try / Buy**.

1. On the **Activate** blade, in the Azure AD Premium P2 section, click **Free Trial** and then click **Activate**.

rgds
Marcin
