### ISSUE TITLE
Can't verify the access to the 'external AKS-hosted service' in 'Lab 09: Configuring and Securing ACR and AKS'

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#117]
# Module: Module 02 - Implement Platform Protection
#### Step: 06 - In the Bash session within the Cloud Shell pane, run the following to retrieve information about the nginxinternal 
                          service including name, type, IP addresses, and ports.

Description of issue:
For some reason, i'm not getting the 'External-IP' of 'nginxinternal'.  All i'm seeing is '<pending>'.  I've even tried to refresh it and redone the steps but same issue. Below is a snapshot of it:

![image](https://user-images.githubusercontent.com/30388154/113846721-ae477180-978e-11eb-963b-003e0833358a.png)

**Comment by polichtm** [comment]
Pls make sure to use the current version of the content on GitHub. 
There was a recent update addressing this particular issue
rgds
Marcin

**Comment by SAIMMINHAS** [comment]
Hi,

Sorry. Not sure where to check the 'version of the content' as i'm only doing these Labs through: 

https://microsoftlearning.github.io/AZ500-AzureSecurityTechnologies/

Thanks.

**Comment by polichtm** [comment]
This has been addressed
rgds
Marcin
