### ISSUE TITLE
Both Install-Package commands are not running

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#118]
# Module: 
#### Step: 7

Description of issue

The PowerShell commands in the markdown doc are in one code block:
Install-Package Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider
Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory

As stated these are in one code block in the markdown document, while there is no problem with that, the way that this is translated into LearnOnDemandSystems LODS is with one T link. This means that when the students click on the link only the first command actually runs. This produces an error later on in the lab.

Solution:
If we could have these commands split into two code blocks in the markdown doc, this would be interpreted as two code block links and could be run separately and this will solve the issues we currently face...

Repro steps:

**Comment by polichtm** [comment]
updated
rgds
Marcin
