### ISSUE TITLE
Can't verify the access to the 'external AKS-hosted service' in 'Lab 09: Configuring and Securing ACR and AKS' #117

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#119]
Hi,

Please DO NOT close this issue without a proper reply. It is linked to:

https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/issues/117#issuecomment-814779214

All i got a reply was this:

polichtm commented 3 days ago
This has been addressed
rgds
Marcin

I don't have a clue where this was addressed and what is the solution to it. Please at least give a link so that i can check.

**Comment by polichtm** [comment]
Pls refer to the commit #117 included in the response to the issue you raised - as per the screenshot below:

![image](https://user-images.githubusercontent.com/10284906/114548725-23eb8b80-9c2e-11eb-8db0-2ab7c0c05ebe.png)

Let me know if any clarification is needed
rgds
Marcin

**Comment by SAIMMINHAS** [comment]
Hi Marcin,

Thanks.

I'll update here again if any issues,

Will test the lab again.

Regards,
Saim
