### ISSUE TITLE
Lab 14 Task 2 Step 3-6 UI Difference

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#121]
# Module: 4
#### Step: 3 -6

UI Difference

#3 Click Secure Score and Click View Recommendations
#4 scroll down and look for Install endpoint protection solution on virtual machine and click it
#5 Select Install on 1VMs
#6 Select Microsoft Antimalware and click Create and then OK

**Comment by polichtm** [comment]
updated
