### ISSUE TITLE
Lab 10, Exercise 3, Step 5 - Cannot convert 'System.Object[]' to the type 'System.String'

### ISSUE THREAD

**Issue by dober-man** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#124]
# Module: 10
#### Step: 00

Description of issue
Step 4: 
PS /home/brad>  $kvName = (Get-AzKeyVault -ResourceGroupName 'AZ500LAB10').VaultName
PS /home/brad>  $kvName
az500kv2051304762
az500kv812344188'

Step 5: 
PS /home/brad>  Set-AZKeyVaultAccessPolicy -VaultName $kvName
Set-AzKeyVaultAccessPolicy: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'VaultName'. Specified method is not supported.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
It appears you have two key vaults in the resource group. There should be only one.
Pls remove the key vault you are not using and give it another try
rgds
Marcin

**Comment by dober-man** [comment]
thank you. not sure how that happened....maybe an accidental double-paste. tyvm

**Comment by polichtm** [comment]
np
rgds
Marcin
