### ISSUE TITLE
Update LAB_01_RBAC.md . Missing powershell command to set set the value of the password within the profile object:

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#126]
# Module: 01
#### Step: 04

Description of issue
. In the PowerShell session within the Cloud Shell pane, run the following to set the value of the password within the profile object:
    ```powershell
 
    ```

There is no command here. It is missing
    ```
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
where specifically are you seeing this?
Here is the content of the GitHub repo at https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/master/Instructions/Labs/LAB_01_RBAC.md :

![image](https://user-images.githubusercontent.com/10284906/119155500-42a92300-ba21-11eb-94d4-3c49eb09c012.png)

rgds
Marcin

**Comment by dpapkin** [comment]
Hi Marcin, strange, I downloaded the zip 2 days ago, Your link contains the updated labs. Thanks.

May I ask you something else?

1. Ensure **PowerShell** is selected in the drop-down menu in the upper-left corner of the Cloud Shell pane.

   >**Note**: To paste copied text into the Cloud Shell, right-click within the pane window and select **Pane**. Alternatively, you can use the **Shift+Insert** key combination.

Where is this  " right-click within the pane window and select **Pane*"?  My students were asking. I dont see it. Feel foolish asking you. I have told them to just right click at the cursor in the cloud shell window.

Thans

David

**Comment by polichtm** [comment]
Hi David,
that was meant to be "Paste" ;)
updated 
rgds
Marcin

**Comment by dpapkin** [comment]
> Hi David,
> that was meant to be "Paste" ;)
> updated
> rgds
> Marcin

Thanks :)

Stay safe!

David
