### ISSUE TITLE
Module 1 Lab 4 Select a VM Size

### ISSUE THREAD

**Issue by LostSailor2021** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#127]
# Module: 01
#### Step: 09

Description of issue: Lab Instructions state "Vm Size Standard_D2s_v3

Repro steps:

1. Follow steps of Task 1 on portal.azure.com
2. When Value = Standard_D2s_v3 try searching for value under "Select a VM size" Notice that the word Standard has been removed from the name. It is now listed as "D2s_v3" without the word Standard in front of it. Searching for just the value=Standard will show results as zero. 

![lab4-3](https://user-images.githubusercontent.com/84743860/119405652-359d6580-bca7-11eb-919a-c92003de6170.JPG)
![lab4-2](https://user-images.githubusercontent.com/84743860/119405655-36ce9280-bca7-11eb-8cca-978ebf95ce94.JPG)
![lab4-1](https://user-images.githubusercontent.com/84743860/119405657-36ce9280-bca7-11eb-8dd8-a972f5d6ea2c.JPG)

**Comment by polichtm** [comment]
It's still Standard...

![image](https://user-images.githubusercontent.com/10284906/119420998-ae161d80-bccb-11eb-9a7c-1e3b4f26393f.png)

rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
rgds
Marcin
