### ISSUE TITLE
05 - Azure AD Privileged Identity Management no choice for permanent assigned

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#128]
# Module: 01
#### Step: 07

Description of issue
Possible GUI drift.
lab states on line 127 **Note**: User aaduser2 is now permanently assigned the Security Administrator role.
but the GUI check box is "Permanently Eligible".
![image](https://user-images.githubusercontent.com/24426530/119438323-7e5e2880-bd52-11eb-9f41-3bf299985f7a.png)

I suggest line 127 **Note**: User aaduser2 is now  Permanently eligible for the Security Administrator role.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
