### ISSUE TITLE
Lab_13_Azure Monitor Logs Get started not displayed

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#131]
# Module: 04
#### Step: 03

Description of issue
 On the Logs blade, click **Get started**.  is not there. Possible GUI drift
![image](https://user-images.githubusercontent.com/24426530/119601825-8b474e80-be1c-11eb-9b42-fd0ebea50739.png

To compensate, 
1. 
I clicked the Category Drop-down, selected Query type,  Example Queries is selected underneath All Queries , and typed "virtual machine" in the search query .

![image](https://user-images.githubusercontent.com/24426530/119602108-090b5a00-be1d-11eb-8315-b8d40e4da3ae.png)

Better sample query for this lab  is "Memory and CPU usage"

I clicked the Category Drop-down, selected Query type,  Example Queries is selected underneath All Queries , and typed "cpu" in the search query  and click on **Run** on "Memory and CPU usage" query.
![image](https://user-images.githubusercontent.com/24426530/119610674-2eec2b00-be2c-11eb-9f66-0a3e2a7a4bd5.png)

)

2. it would be more useful if any query produced results for the students.  I suggest we generate some CPU load since one of the counters is Process(\*)\%Processor Time.
This is from one of  my legacy MSFT  MCSA server classes, many years ago, cpuloop.bat
There is a newer version , cpuloop.vbs, but I cant find it.

In another Portal window,  select myVM from Virtual Machines, in the Operations section, click on **Run command** . Click on "RunPowershellScript" and paste the following and click **Run**:
cmd
:loop
dir c:\ /s > SWAP
goto loop

![image](https://user-images.githubusercontent.com/24426530/119611471-4f68b500-be2d-11eb-82a1-14c833e90fd0.png)

The script will eventually timeout but will generate some load,

Switch back to the Log Analytics window and Click on **Run** again

If there is no data, wait several minutes, at least 10 until you see some data

![image](https://user-images.githubusercontent.com/24426530/119611812-c00fd180-be2d-11eb-9fcd-788af7171ba9.png)

David Papkin

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
