### ISSUE TITLE
Created VM in Module 04 - Lab 14 myVM is not listed for JIT VM Access

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#132]
# Module: 04
#### Step: 02

Description of issue
myVM is not listed for JIT VM Access. All 9 of my students for this class had the same issue.

![image](https://user-images.githubusercontent.com/24426530/119935070-73f19800-bfb9-11eb-8034-b164908639a8.png)

![image](https://user-images.githubusercontent.com/24426530/119934987-4f95bb80-bfb9-11eb-981c-ea2681358139.png)

![image](https://user-images.githubusercontent.com/24426530/119935097-8370e100-bfb9-11eb-8416-16e90d7c3c93.png)

![image](https://user-images.githubusercontent.com/24426530/119935139-94b9ed80-bfb9-11eb-9a0c-5854bbc793fa.png)
![image](https://user-images.githubusercontent.com/24426530/119935176-a1d6dc80-bfb9-11eb-8df4-15df4a1b17c1.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
unfortunately I cannot reproduce this issue. How long did you wait for the VM to appear? 
Which subscription and which Azure region were you and your students using?
rgds
Marcin

**Comment by dpapkin** [comment]
hi, all my 9  students had the same behavior . east us

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by polichtm** [comment]
Hi David
Here is what I'm seeing - I'm using Azure Pass and East US as well
![image](https://user-images.githubusercontent.com/10284906/120653863-1e047080-c44f-11eb-9fc8-9848fbf9126d.png)
rgds
Marcin

**Comment by dpapkin** [comment]
Maybe the azure admin had some bandwidth limits on East US t that time. Any ideas on another region that has good capacity for Azure Pass? Uk South? Please note I am in Singaporr, maybe they do maintenance in those hours that affects the performance?

**Comment by polichtm** [comment]
Hi David,
possibly - although this should ultimately work after a delay. 
I'm using East US most of the time - although admittedly typically not during the regular business hours in Singapore
rgds
Marcin

**Comment by dpapkin** [comment]
Was a big deal, had some important customers in the class. All 9 of them had the same behavior. I will retry it with a new pass. I am teaching this class again june 21

**Comment by polichtm** [comment]
Hi David,
pls let me know how this works out.
Btw. you might want to try turning Defender on and off, this seems to speed things up a bit
rgds
Marcin

**Comment by FireyJoe** [comment]
I ran into this issue in testing as well. I waited for more than an hour before visiting the VM's "Configuration" blade and enabling JIT access from the button at the top. I returned to the security center "Just-in-time VM access" page and refreshed it and the VM switched from "unsupported" to "configured" immediately.

**Comment by abhimanmohan** [comment]
Hi My VM is showing in unsupported, please help in resolving this issue
![image](https://user-images.githubusercontent.com/64397100/129441916-203e335e-0981-4856-ba11-f7f72f5a6c57.png)
