### ISSUE TITLE
Lab 15 Azure Sentinel Logic App Designer GUI drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#133]
# Module: 04
#### Step: 3

Description of issue
1. On the **Azure Sentinel** blade, click **Connect workspace** is now 
 On the **Azure Sentinel** blade, click **Create Azure Sentinel**

#### Step: 12

The logic app designer now asks for additional info
Alert- Get Incident (Preview)
*Specify subscription id
*Specify resource group
*Specify workspace Id
*Specify alert id
Alert- Get accounts (Preview)
*Entities list
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
here is what I'm seeing at step 12:
![image](https://user-images.githubusercontent.com/10284906/120640879-fdcdb500-c440-11eb-9aa1-f5f2b15c581b.png)

pls advise what specifically you're referring to
rgds
Marcin

**Comment by polichtm** [comment]
Hi David,
regarding task 4 step 12, you can simply accept the defaults
The instructions have been updated to provide more clarity
rgds
Marcin
