### ISSUE TITLE
Module 01 - Manage Identity and Access Task 6 Validate MFA configuration

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#135]
# Module: 01
#### Step: 08

Description of issue
GUI drift.

Now asks for additional authentication method

1. On the **Keep your account secure** page, ensure that the verification was successful and click **Next**.
1. On the **Keep your account secure** page, click **Done**.

After successful verification of SMS, it asks for a second method instead of "Done"
![image](https://user-images.githubusercontent.com/24426530/122722341-2d374b00-d2a4-11eb-84a4-f2aca53d7bb2.png)

I suggest Email, since not everyone can install the Authenticator App.

![image](https://user-images.githubusercontent.com/24426530/122722581-79828b00-d2a4-11eb-85e5-f7dd51056c2c.png)

SHOULD BE

1. On the **Keep your account secure** page, ensure that the verification was successful and click **Next**.

1. On the **Keep your account secure** page, click **I want to use a different  method** and select Email from the drop down list aNd click **Confirm** and then enter the email address you will use and click *Next**. Enter the code you received in the email and then click **Done*

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
