### ISSUE TITLE
05 - Azure AD Privileged Identity Management  aaduser2 not permanently eligible

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#136]
# Module: 01
#### Step: 07

Description of issue
aaduser2 is not permanently eligible. expires in 3 months
![image](https://user-images.githubusercontent.com/24426530/122858968-d0906a80-d34d-11eb-8802-6cc27316fd41.png)

![image](https://user-images.githubusercontent.com/24426530/122859007-e00fb380-d34d-11eb-9bad-c7b00eed2967.png)

![image](https://user-images.githubusercontent.com/24426530/122859050-f3228380-d34d-11eb-91d9-c76c8d91b64a.png)

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by serling1962** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.
