### ISSUE TITLE
UI change (SQL Auditing)

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#137]
# Module: 03
#### Step: 04

Description of issue

Auditing onboarding UI changed

**Comment by R-C-Stewart** [comment]
I updated the lab instructions and created a Pull Request.  Waiting for the end of week, to accept them into the repo, so we don't disrupt any on-going labs.

**Comment by R-C-Stewart** [comment]
Should be fixed now.  Thanks for the Issue su
