### ISSUE TITLE
LAB_15_Azure Sentinel Ex 1 Task 2 UI drift 

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#138]
# Module: 04
#### Step: 03

Description of issue

UI drift

 On the **Azure Activity** blade, click the **Configure Azure Activity logs** link**
changed to **Launch Azure Policy Assignment wizard**

![image](https://user-images.githubusercontent.com/24426530/123214001-48e75f00-d4f9-11eb-84c3-3ccaf101164b.png)

Need to redo this section. Quite different.

Students unable to proceed.

Repro steps:

1.
1.
1.

**Comment by StevenLODS** [comment]
Bumping this

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the course

**Comment by dpapkin** [comment]
@MOC-Labs-Review  The GUI is quite different. Please take a look . I am running this class again next week with important customer. Escalate

**Comment by dpapkin** [comment]
> Bumping this

The GUI is quite different. Please take a look . I am running this class again next week with important customer. Escalate
