### ISSUE TITLE
Lab 15 - Analytic rule for Sentinel does not create incident

### ISSUE THREAD

**Issue by lodivanelswijk** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#139]
# Module: 04
#### Step: 06

The analytic rule created in this step does not always trigger an incident due to a case-sensitive query.

The query in question:

```
AzureActivity
 | where ResourceProviderValue == "Microsoft.Security" 
 | where OperationNameValue == "Microsoft.Security/locations/jitNetworkAccessPolicies/delete" 
```

In Log Analytics, the event triggered in the lab is logged with ResourceProviderValue `MICROSOFT.SECURITY` and OperationNameValue `MICROSOFT.SECURITY/LOCATIONS/JITNETWORKACCESSPOLICIES/DELETE`. Because of the case-sensitive string comparison in the query, the incident that the analytic rule is supposed to raise is not created.

Solution: change the query to a case-insensitive string comparison, i.e.:

```
AzureActivity
 | where ResourceProviderValue =~ "Microsoft.Security" 
 | where OperationNameValue =~ "Microsoft.Security/locations/jitNetworkAccessPolicies/delete" 
```

**Repro steps**

The issue can be reproduced by following the steps in the lab.

**Comment by polichtm** [comment]
updated
rgds
Marcin
