### ISSUE TITLE
AAD Tenant Creation Experience updated

### ISSUE THREAD

**Issue by tofusgh** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#145]
# Module: 01
#### Step: 02

Description of issue

The Azure AD interface has been updated and we need to direct users through the "Manage Tenants" experience in AAD as there is no longer a "Create a tenant" button within the AAD overview blade.
Repro steps:

1.
1.
1.

**Comment by StevenLODS** [comment]
I have submitted a pull request to have this updated.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.
