### ISSUE TITLE
Module 03: Lab 12, where the SQL Management Studio is not populating the KeyVault

### ISSUE THREAD

**Issue by tofusgh** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#146]
# Module: 03
#### Step: 15

Description of issue

Task: 5, Step: 15: 
On the Master Key Configuration page, select Azure Key Vault, click Sign in, when prompted, authenticate by using the same user account you used to provision the Azure Key Vault instance earlier in this lab, ensure that that Key Vault appears in the Select an Azure Key Vault drop down list, and click Next.

**The interface of Management Studio is broken and does not allow for users to select the subscription their Key Vault in.**

Repro steps:

![2021-07-16_10-16-45](https://user-images.githubusercontent.com/31666473/125963385-d2ca70ea-8c1d-4309-b8cd-a3a5c016929a.png)

The solution seems to use hotkeys in the UI for this step: Use the Keyboard going where the subscription “button” is supposed to be with the Tab key and the arrows. 

This lab doesn't display our products the best and maybe should be reconsidered but for now adding a note for this solution would be helpful

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review resolved this issue with PR #192

**Comment by serling1962** [comment]
MOC-Labs-Review resolved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/192

**Comment by serling1962** [comment]
MOC-Labs-Review resolved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/192

**Comment by serling1962** [comment]
MOC-Labs-Review resolved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/192
