### ISSUE TITLE
Lab 06: Task 2:Use an ARM template to deploy an Azure VM hosting an Active Directory domain controller Step 1: Github link broken returns 404

### ISSUE THREAD

**Issue by tofusgh** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#151]
# Module: 00
#### Step: 00

Description of issue
Lab 06: Task 2:Use an ARM template to deploy an Azure VM hosting an Active Directory domain controller Step 1: Github link broken returns 404
Repro steps:

1.
1.
1.

**Comment by thegreatmayank** [comment]
Maybe you are coping (.) also, that is at the end of the link. try the blow link:-

https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain

Regards,

Mayank

**Comment by tofusgh** [comment]
If you right click the link and say open in new tab you get a 404.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thegreatmayank** [comment]
I don't know how the above link was appended with so much info can you please try once more with the below link:

https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain

or click [here](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain)

see if this works.

**Comment by tofusgh** [comment]
It works here but not from the instructions in the lab...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cdanvergara** [comment]
Experiencing the same issue today, the link on the instructions seems to be ok. It's the right one:
https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/active-directory/active-directory-new-domain
But, there's something wrong with format. When you click on it, it's not properly formatted.
Getting the same 404 error:
![image](https://user-images.githubusercontent.com/6410720/131563065-8cab6c3c-a4e4-404d-ae01-9342f77da02a.png)

By looking at the url, I can tell it's duplicating the url and adding some %60 characters on the url:
![image](https://user-images.githubusercontent.com/6410720/131563267-35c573db-3d0e-43a0-8a88-d11b135967ba.png)
We need to solve this urgently!

**Comment by FireyJoe** [comment]
It seems the link is being redirected. The address shown is correct, and if copied into the VM as plain text it will work.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by serling1962** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.
