### ISSUE TITLE
New-PSDrive command missing '-scope Global'

### ISSUE THREAD

**Issue by simonliu8168** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#153]
# Module: 03
#### Step: 06

Description of issue

The New-PSDrive PS command is missing '-scope Global' as a parameter, Z drive won't show on file explore with existing command, it should be:

New-PSDrive -Name Z -PSProvider FileSystem -Root "\\<storage_account_name>.file.core.windows.net\my-file-share" -scope Global -Persist

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the lab

**Comment by serling1962** [comment]
MOC-Labs-Review did not encounter this issue while running the lab
