### ISSUE TITLE
My VM is in Unsupported , so I am not able to move forward 

### ISSUE THREAD

**Issue by abhimanmohan** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#155]
# Module: 04
#### Step: 03

Description of issue
![image](https://user-images.githubusercontent.com/64397100/129441987-d8fba342-e624-4025-bae3-22359ac4fa17.png)

Repro steps:

1.
1.
1.

**Comment by thegreatmayank** [comment]
Hi Abhimanmohan,

I hope you have ensured that nothing of the case given under unsupported tab i.e. "classic, no associated NSG, or JIT policy is turned off on their scope" is the case.

**Comment by abhimanmohan** [comment]
After 3 hr it came to Not configured from unsupportable , is it normal ?

**Comment by thegreatmayank** [comment]
yes, sometimes it happens. You may apply JIT from the VM blade too
