### ISSUE TITLE
Run Command not found in VM blade 

### ISSUE THREAD

**Issue by abhimanmohan** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#157]
# Module: 04
#### Step: 06(ii)

where is run command script in Azure portal?

![image](https://user-images.githubusercontent.com/64397100/130397530-73cc705e-88c6-4105-94d0-98f09f8efaba.png)

I can see only these options:

![image](https://user-images.githubusercontent.com/64397100/130397619-aad6539d-60a9-4924-a876-8f38d433af7a.png)

Description of issue

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review solved this issue with PR #193

**Comment by serling1962** [comment]
MOC-Labs-Review solved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/193
