### ISSUE TITLE
Switching directories has changed - lab is no longer correct

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#161]
# Module: 1
#### Step: 2 and 3

Description of issue
The lab no longer reflects the screen
Repro steps:
Step 2: Should read something like this "Click on the SWITCH button associated with the new AdatumLab500-04 directory"
Step 3: Search for and Azure Active Directory and press the Enter key
![Screenshot 2021-09-13 165133](https://user-images.githubusercontent.com/18732050/133037113-680919d4-bf50-43eb-8faf-254ce9f35429.jpg)

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review pull request solved for this Issue.

**Comment by serling1962** [comment]
MOC-Labs-Review resolved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/185
