### ISSUE TITLE
Wrong section listed in instructions

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#162]
# Module: 1
#### Step: 4

Description of issue
Instruction is incorrect 
**Tasks** should be changed to **Manage**
Repro steps:
Step 4 should be changed to: 
4. On the **Privileged Identity Management** | **Quick start** blade, in the **Manage** section, click **![Screenshot 2021-09-13 170102](https://user-images.githubusercontent.com/18732050/133066415-b6b12452-895c-4702-861d-c44dc9f46347.jpg)**.

**Comment by brentd09** [comment]
4. On the Privileged Identity Management | Quick start blade, in the Manage section, click Azure AD Roles and Hit ENTER

Im not sure why this was trimmed in mt initial post

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review pull request solved for this Issue.

**Comment by serling1962** [comment]
MOC-Labs-Review solved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/186
