### ISSUE TITLE
Replace Mod 1 Lab 6 Task 2 Step 1

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#163]
The Azure AD Connect now requires 1.2 TLS and the Template is 2016 you could have the student apply reg keys here
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-tls-enforcement

Or I did this

1. goto Virtual Machines in Azure Portal and Click + Create, Virtual Machine.
2. On image click see all images, Click Select Under Windows Server
3. Click Windows Server 2022 Datacenter Gen1
4. on Availability options select NO
5. Ignore steps 2, 3 and 4 and, use Step 5 settings but ignore the domain entries and go with the default settings for the rest and click
Review and Create, Click Create

Create 2022 Windows Server using lab settings

6. login to your 2022 server after it is running with  RDP and create a file in notepad
copy the following to notepad and save to file to C:\m6dcpromo.txt

[DCInstall] 
ReplicaOrNewDomain=Domain 
NewDomain=Forest 
NewDomainDNSName=adatum.com 
ForestLevel=3 
DomainNetbiosName=adatum
DomainLevel=3 
InstallDNS=Yes 
ConfirmGc=Yes 
CreateDNSDelegation=No 
DatabasePath="C:\Windows\NTDS" 
LogPath="C:\Windows\NTDS" 
SYSVOLPath="C:\Windows\SYSVOL" 
SafeModeAdminPassword=P@ssw0rd1234 
RebootOnCompletion=Yes

7. At an elevated command prompt run this  

dcpromo.exe /unattend:C:\m6dcpromo.txt

**Comment by R-C-Stewart** [comment]
We updated the Virtual Machine to be Gen 2 and this appears to fix the issue.
