### ISSUE TITLE
Lab 8: Mismatch between instructions and template - different sku

### ISSUE THREAD

**Issue by Villae** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#166]
# Module: 2
#### Step: 4

Lab instructions says that ">**Note**: Review the content of the template and note that it deploys an Azure VM hosting Windows Server 2019 Datacenter.", but template uses 2016 Datacenter.

Lines:

https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/fb56e8fec5f59b4f73fb1dd16e12d9aac200ee21/Instructions/Labs/LAB_08_AzureFirewall.md#L64

https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/71850cf792e7a59cf81dbc171fb88fb1d1a79bf4/Allfiles/Labs/08/template.json#L418

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this issue.
