### ISSUE TITLE
Lab 14: Azure Security Center is now Azure Defender for Cloud

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#168]
# Module: 4
#### Step: several

Description of issue:
Azure Security Center is now Microsoft Defender for Cloud. There are several diferences in the beginning on the lab also. Not just the name but we also have major UI changes. 
We need to refresh the lab instructions.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review solved this issue with PR #195

**Comment by serling1962** [comment]
Resolved.
