### ISSUE TITLE
Lab 11 : Exercise 1 : Task 2 : The Security Center has been replaced by Microsoft defender by Cloud

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#169]
# Module: Lab 11: Securing Azure SQL Database
#### Step: 4 : On the server blade, in the Security section, click Security Center.

Description of issue
The Security Center is no longer available under SQL Server | Security. It has been replaced by "Microsoft defender by Cloud".

![image](https://user-images.githubusercontent.com/47213023/142018146-e196b579-5e68-4acc-9688-e267ba1a4511.png)

Can we please update the instructions accordingly? Thanks.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review has resolved this issue with PR #192

**Comment by serling1962** [comment]
MOC-Labs-Review has resolved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/192
