### ISSUE TITLE
Lab 01: Challenging on LOD/Skillable to create users

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#176]
# Module: 01
#### Step: 00

Description of issue
In Lab1: Creating users and activiting P1/P2 licenses is not available to students on LOD/Skillable.
Better start with Lab 4,  create a new tenant, and then try to finish Lab 1.
The solution to create a E5 trial is not working. From the hosted lab, students can't create this new tenant.
Better to do it like lab 4 or like Lab 6 in the AZ-204 course were is works now on LOD.

Repro steps:

1.
1.
1.

**Comment by molenaar** [comment]
Also in the flow of the theory in Module 1 it seems better to start with Lab 4 instead of Lab 1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.

**Comment by serling1962** [comment]
MOC-Labs-Review did not encounter this Issue while running the course.
