### ISSUE TITLE
Module 2 Lab 8 Firewall Premium selected by default and how about Firewall Policies?

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#178]
# Module: 02
#### Step: 00

Description of issue
Azure Firewall Premium is out of preview and now selected by default. 
Make sure Azure Firewall Standard is Selected. In Premium you cannot select classic rules.

When will this Lab be updated to use Use a Firewall Policies? Firewall rules are classic now.

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review solved this issue with PR #189

**Comment by serling1962** [comment]
MOC-Labs-Review solved this issue with PR https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/pull/189
