### ISSUE TITLE
Lab10-Exercise 3 -Task 5 - Issue Enabling Always Encrypted in SSMS

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#179]
# Module: 03
#### Step: 14

Description of issue

Impossible to complete the always encrypt configuration in SSMS. We get the following error:

https://az500stacccv.blob.core.windows.net/files/MicrosoftTeams-image.png

So far, we tried the following:

- Clearing all the credentials on the vm
- Reboot the vm 
- Verified the firewall settings

Repro steps:
Exercise 3
Task 5

14. On the Column Selection page, select the SSN and Birthdate columns, set the Encryption Type of the SSN column to Deterministic and of the Birthdate column to Randomized, and click Next.

15.On the Master Key Configuration page, select Azure Key Vault, click Sign in, when prompted, authenticate by using the same user account you used to provision the Azure Key Vault instance earlier in this lab, ensure that that Key Vault appears in the Select an Azure Key Vault drop down list, and click Next.

**Comment by molenaar** [comment]
Yes, we are stuck on the issue too. This lab worked for year, very frustrating and the error message is unclear.
SSMS is the most recent version. 

We also added the user (already owner) as Key Vault contributor to the resource group.

**Comment by robmcnair** [comment]
Has there been an update to this issue?

**Comment by MNuijen** [comment]
What s the eta for a fix?

**Comment by cdanvergara** [comment]
> Has there been an update to this issue?
> What s the eta for a fix?

No ETA, the workaround is to use PowerShell to enable AlwaysEncrypted instead of SSMS.
The root caused has not been identified yet, so no clear solution.... LODS is validating if it makes sense to update the instructions to use PowerShell.

**Comment by jians1900** [comment]
Key Vault Access Policy, unselect  key permissions in Rotation policy operations section.
https://s1206.blob.core.windows.net/downloads/lab10.png

**Comment by nestorreveron** [comment]
> Key Vault Access Policy, unselect key permissions in Rotation policy operations section. https://s1206.blob.core.windows.net/downloads/lab10.png

Thanks a lot!

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review has solved this issue with PR #191

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review resolved this issue with PR #192
