### ISSUE TITLE
Lab 12: Cannot find Storage service tag

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#180]
# Module: 03
#### Step: 03

Description of issue
Cannot select storage in the outbound security rule. Am I missing some rights?

![image](https://user-images.githubusercontent.com/10166617/143464889-9d190e3f-76d1-4aeb-a6cc-1e3a492578d7.png)

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the lab
