### ISSUE TITLE
May I know how to get slides of this lab?

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#181]
Hi Experts,

I am MS FTE, I am wondering if I can have access to the training materials in this Lab.

Any guidance on how to do it is highly appreciated.

Thanks

**Comment by serling1962** [comment]
Hello Cengxiye,

Microsoft Azure (AZ-500) training materials such as the PowerPoint decks are limited to Microsoft Techincal Trainers,  Relative AZ-500 training materials are available on Microsoft Learn at https://docs.microsoft.com/en-us/learn/certifications/azure-security-engineer/?tab=tab-learning-paths.

Best regards,

-Serling.

**Comment by serling1962** [comment]
Hello Cengxiye,

Microsoft Azure (AZ-500) training materials such as the PowerPoint decks are limited to Microsoft Techincal Trainers, Relative AZ-500 training materials are available on Microsoft Learn at https://docs.microsoft.com/en-us/learn/certifications/azure-security-engineer/?tab=tab-learning-paths.

Best regards,

-Serling.
