### ISSUE TITLE
Step Can be Removed

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#197]
# Module: 04
#### Step: 4

Description of issue
There is no longer a Pricing Tab, the pay as you go option is now selected by default. Step 4 could be removed.

"Click Next: Pricing tier >, on the Pricing tier tab of the Create Log Analytics workspace blade, accept the default Pay-as-you-go (Per GB 2018) pricing tier, and click Review + create."

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not experience this Issue.
