### ISSUE TITLE
All the hardcoded passwords should be removed from Labs.  RDP is not blocked by default in the labs and are vulnerable.

### ISSUE THREAD

**Issue by hansze** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#199]
# Module: 00## Lab: 6 
##### Step: 05 

Admin Password | Pa55w.rd1234

I ran one of the previous labs and did not think much of this however 10min into the lab I RDP'd into the VM and saw portscanner running as well as NLBrute on desktop with the files of the compromised users and passwords on the VM. Early in the Kill-Chain but not good. Ironic that this a AZ500 lab on security. 

Recommendation is to remove ALL passwords and have students generate their own using perhaps the following bit of code:

# Add-Type might be needed prior - Will only work with PS 5.1 (.NET Desktop - not core i.e 7.x)
$pwd = [System.Web.Security.Membership]::GeneratePassword(12,2)
$sspwd = ConvertTo-SecureString -String $pwd  -AsPlainText -Force # used when creating user via New-azAdUser as securestring is needed. 
$pwd | Set-Clipboard # in order to make easy to set when creating user via GUI

**Comment by serling1962** [comment]
Resolved by executing the following instructions: 
Please use your personal password created in Lab 04 > Exercise 1 > Task 1 > Step 9
