### ISSUE TITLE
Labs Structure

### ISSUE THREAD

**Issue by thepaulmacca** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#21]
The structure of the labs in this repo compared to the previous one is a lot different. Each lab was in it's own module folder, this makes things a lot cleaner and easier to navigate in my opinion. Is this going to be changed?

**Comment by azharkhuwaja** [comment]
Agree.

Lab 1 to Lab 6 -> Module 1
Lab 7 to Lab 9 -> Module 2
Lab 10 to Lab 12 -> Module 3
Lab 13 to Lab 15 -> Module 4

**Comment by thepaulmacca** [comment]
There also seems to be **a lot** more modules in the older repo

**Comment by polichtm** [comment]
Hi Paul, 
appreciate the suggestion. I'm not sure what you mean by "easier to navigate" - considering that currently there is a single folder with all instruction files in it (so effectively, there is nothing to navigate - which you would have to go through if you create a folder structure). 
Could you clarify?
rgds
Marcin

**Comment by thepaulmacca** [comment]
Hi Marcin, what I mean is that it should be like the old repo where the labs are in its relevant module folder, so if you’re interested in labs for Module 2 for example, just go into that folder and the labs are there

Right now in this repo, all I see is a bunch of labs, with no idea of what module they’re referring to, until I go into each one, which doesn’t seem very intuitive to me compared to the previous repo

Thanks
Paul

________________________________

**Comment by polichtm** [comment]
Hi Paul,
Does this mean you would want to have 4 folders corresponding to four modules - with multiple md files in each (as suggested by @azharkhuwaja above)? 
How do you envision the corresponding folder structure for lab files?
rgds
Marcin

**Comment by thepaulmacca** [comment]
Hi Marcin yes, similar to the old repo basically

Thanks
Paul

________________________________

**Comment by polichtm** [comment]
Hi Paul,
Is this what you are referring to?
https://github.com/MicrosoftLearning/AZ-500-Azure-Security/tree/master/Allfiles/Labs
rgds
Marcin

**Comment by thepaulmacca** [comment]
Hi Marcin no, I mean this one https://github.com/MicrosoftLearning/AZ-500-Azure-Security/tree/master/Instructions/Labs

Thanks
Paul

________________________________

**Comment by polichtm** [comment]
Hi Paul, 
I gather I wasn't clear enough. 
I understand your intention regarding the markdown files containing instructions. 
What I'm referring to are the lab files (templates, scripts, etc.)
rgds
Marcin

**Comment by thepaulmacca** [comment]
Ah right we’ve got our wires crossed here then :)

I’m referring to the instructions, not the files

Thanks
Paul

________________________________

**Comment by staleycyn** [comment]
This course only has 4 modules and 15 labs. The [HTML page](https://microsoftlearning.github.io/AZ500-AzureSecurityTechnologies/) clearly shows the labs in each module. Additionally, each Module's slide deck has a placeholder for each lab. We currently have several lab hosters that are pulling instructions from this repository. A folder change will require them to be notified and may cause a classroom disruption. I will put this on our list for future changes, but we will not be changing this at this time.

**Comment by thepaulmacca** [comment]
I'm going to close this issue now as it's been open for a while and I'm not studying for this exam anymore
