### ISSUE TITLE
lab 13   Log Analytics Agent doesnt connect. Stays in "Connecting "state

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#218]
# Module: 4
#### Step: 05

Description of issue

 Log Analytics Agent doesnt connect. Stays in "Connecting "state

I waited 24 hours. Using East US region.

I  managed to get it working by doing the following troubleshooting procedure. Perhaps you might want to list this.
***
Open PowerShell prompt as Administrator on the machine where Log Analytics Agent is installed.
Navigate to the directory where the tool is located.
cd "C:\Program Files\Microsoft Monitoring Agent\Agent\Troubleshooter"
Execute the main script using this command:
.\GetAgentInfo.ps1
Select 1) Agent not reporting data or heartbeat data missing
Select 3) Repair
Answer Y when prompted
Powershell Window will close

***
[Troubleshoot issues with Log Analytics agent for Windows - Azure Monitor | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agent-windows-troubleshoot)
[https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agent-windows-troubleshoot](url)
Repro steps:

1.
1.
1.

David Papkin

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not experience this Issue.
