### ISSUE TITLE
Lab Demo Recording

### ISSUE THREAD

**Issue by cheahengsoon** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#23]
May I ask about when will update the Lab Demo Recording for AZ-500?

https://github.com/MicrosoftLearning/Lab-Demo-Recordings/blob/master/AZ-500.md

Thank you

**Comment by staleycyn** [comment]
I do not have a timeline for the lab videos. It may not even be something we do. Videos were provided during a time when Azure access was restricted that has now been resolved.
