### ISSUE TITLE
Module 9 / Exercise 1/Task 8/Step 04

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#24]
# Module: 09
#### Step: 04
This line should be modified:
"replace the <internal_IP> placeholder with the **name** you identified in the previous task"
modified line is:
"replace the <internal_IP> placeholder with the **private IP address** you identified in the previous task"

Step: 05
"Close the Cloud Shell pane."
Should be modified with the following due to use of curl in earlier step showing a Nginx html file:

"Type **exit** and then close the Cloud Shell pane".

**Comment by polichtm** [comment]
updated
