### ISSUE TITLE
Lab 12 markdown tables are not rendering correctly because of a typo..

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#249]
# Module: 3
#### Step: 8 and 11

Description of issue
The markdown tables have not been formatted correctly which hides the actual content on the table once the MD is rendered. 

Please remove the extra | symbol on both steps 8 and 11 tables for the "Destination Service Tag",
and while you are there please remove the ** from the table  "Destination Service Tag" table heading as it does not need to be there

Repro steps:

Your table should look like this 

## Step 8
    |Setting|Value|
    |---|---|
    |Source|**Service Tag**|
    |Source service tag|**VirtualNetwork**|
    |Source port ranges|**\***|
    |Destination|**Service Tag**|
    |Destination service tag|**Storage**|
    |Destination port ranges|**\***|
    |Protocol|**Any**|
    |Action|**Allow**|
    |Priority|**1000**|
    |Name|**Allow-Storage-All**|

## Step 11
    |Setting|Value|
    |---|---|
    |Source|**Service Tag**|
    |Source service tag|**VirtualNetwork**|
    |Source port ranges|**\***|
    |Destination|**Service Tag**|
    |Destination service tag|**Internet**|
    |Destination port ranges|**\***|
    |Protocol|**Any**|
    |Action|**Deny**|
    |Priority|**1100**|
    |Name|**Deny-Internet-All**|

**Comment by brentd09** [comment]
Step 13 also has the same issue... I find its a good idea to make sure the table works before duplicating it as it appears here with the same error in each table :))

**Comment by serling1962** [comment]
Removed all ** instances in module 3, at steps 8, 11, and 13.
