### ISSUE TITLE
Connecting to the Public VM is impossible - no NSG was created to allow this

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#250]
# Module: 3
#### Step: 03

Description of issue
This says that the access relys on the precreated NSG for access however because the VM was created without the 3389 port initially there is no precreated NSG.

Later in the lab when you try to connect it does not work and so we had to create our own NSG and associate it to the public machine to get access via RDP.

Please add the steps to create the Public NSG to allow RDP access.
 
Repro steps:

1.
1.
1.

**Comment by steevaavoo** [comment]
This remains an issue - not clear why this was closed.

**Comment by adamrushuk** [comment]
This issue still exists. Why has this been closed?
