### ISSUE TITLE
Unable to set Storage as Destination Service Tag

### ISSUE THREAD

**Issue by ZekeStarr** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#253]
# Module: 3
##### Step: 08

![image](https://user-images.githubusercontent.com/33165238/167715431-31800613-c07d-49e0-9639-bba8dca52329.png)

There is no 'storage' option available on the Destination service tag drop-down.

**Comment by serling1962** [comment]
The destination service tag drop-down is available for selection in Azure as instructed.
![image](https://user-images.githubusercontent.com/91347931/169805522-667bba49-f85a-4100-bec4-f32c3412ed90.png)
