### ISSUE TITLE
Need to uncheck "Release" option in Azure Key Vault Access Policy

### ISSUE THREAD

**Issue by prym0rdial** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#254]
# Module: 03
#### Step: 09

Description of issue
During the Access Policy creation, selecting all minus **Rotation Policy Operations** leaves 17 total options checked. When trying to connect SQL Server to the Azure Key Vault later in the lab, Exercise 3 - Task 5 - Step 14, it throws an "invocation" error for "Release". Unchecking the "Release" option resolves this issue in SQL Server.

Repro steps:

1. Follow lab instructions as normal through Exercise 3 - Task 5- Step 14
2. Authenticate to the Azure Key Vault during this step, 
3. An error will pop up that reads, "Exception has been thrown by the target of an innvocation. Release (Microsoft.SQLServer.Management.ServiceManagement)."

**Comment by xymvl4t3d** [comment]
Yup, this works. Had the same error too.

**Comment by serling1962** [comment]
Note: While performing the encryption if any error thrown like Exception has been thrown by the target of an innvocation related to Rotary(Microsoft.SQLServer.Management.ServiceManagement) then make sure the Key Permission's values of Rotation Policy Operations are unchecked, if not in the Azure portal navigate to the Key Vault >> Access Policies >> Key Permissions >> Uncheck all the values under the Rotation Policy Operations .

**Comment by prym0rdial** [comment]
Not to be rude, but did you even read my issue? This is not related to a
"Rotary" error but a "Release" error. If you follow my repro steps, you'll
find that there is a new option in the key permissions category that is not
detailed in the lab.

**Comment by TesterTesterson1004** [comment]
I was looking at reports that this workaround worked for some students, but a didnt for a small subset.  I ran my own test instance, verified the above, and yet still ran into the issue.  Uncertain what might lead to the intermittency, but here is yet another alternate workaround:

After Step 11, but before Step 12, run the following query in **SSMS**.  Be sure to replace the value in **KEY_PATH** below with the proper value for your instance, which can be found in **Key Vault** >> **Keys** >> **MyLabKey** >> **Current version** >> **Key Identifier**:
 
```sql     
CREATE COLUMN MASTER KEY [CMK_Auto1]
WITH
(
KEY_STORE_PROVIDER_NAME = N'AZURE_KEY_VAULT',
KEY_PATH = N'https://<keyvaultname>.vault.azure.net/keys/MyLabKey/<keyid>'
)
GO
```

After running this query successfully, continue with the lab steps, replacing **Step 15** with the following:
 
1. On the **Master Key Configuration page**, in the **Select generate column master key** dropdown, select **CMK_Auto1** and then select **Next**.
