### ISSUE TITLE
Lab 6 DSC error regarding invalid password

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#267]
# Module: 01
#### Step: 06

Description of issue
When deploying the VM it is retuning an error: 
... The password supplied to the Desired State Configuration resource MSFT_xADDomain is not valid ...
Repro steps:
I have tried to replicate the lab to see if the error was through a configuration error but I also get the same error as all of the class participants.

**Comment by crudooper** [comment]
Same error for me :

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'CreateADForest'. Error message: \"DSC Configuration 'CreateADPDC' completed with error(s). Following are the first few: The password supplied to the Desired State Configuration resource MSFT_xADDomain is not valid. The password cannot be null or empty. The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
    }
}

**Comment by serling1962** [comment]
Reported as resolved by Skillable.
