### ISSUE TITLE
Lab 6 deployment failure

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#268]
# Module: 01 Manage Identity and Access
#### Step: 06

When attempting to deploy the ARM template, the deployment fails with the message "subscription xxxx-xxx-xxxx-xxxx is not registered with NRP"

![image](https://user-images.githubusercontent.com/48496971/175315508-cb259f9e-4d69-4ba5-93f0-be2664be5dcf.png)

**Comment by serling1962** [comment]
Resolved.  

No further related anomalies or issues have been reported by MTTs that are running existing classes using the posted lab instructions.
