### ISSUE TITLE
Lab 6 auto deploy button is fake

### ISSUE THREAD

**Issue by HoiDam** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#269]
# Module: az-500
#### Step: N/A

Description of issue

Repro steps:

1. These 3 buttons are not doing their jobs. They are just linking to the badge url. Please fix
![image](https://user-images.githubusercontent.com/66233626/176135191-aa4630a3-15ae-41dd-b44b-0876e110a225.png)
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/master/Allfiles/Labs/06/active-directory-new-domain/README.md

**Comment by Potse** [comment]
Perhaps this is the right one? Please comment on [this link](https://azure.microsoft.com/nl-nl/resources/templates/active-directory-new-domain/)!

**Comment by HoiDam** [comment]
WONT FIX
