### ISSUE TITLE
Lab 14: Azure has changed

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#273]
# Module: 00
#### Step: 05

Description of issue

In this step, Azure seems to have changed, as there is no entry w/port 22.  There is, however, an entry for port 3389:

![image](https://user-images.githubusercontent.com/49700217/185808300-5ba4ae46-54c9-4c21-8045-dac3f9dee1c8.png)

**Comment by serling1962** [comment]
Port 22 is visible at the following navigation:

Home > Microsoft Defender for Cloud | Workload protections > Just-in-time VM access

![JIT_VM_access_configuration_Port_22_3389_5985_5986](https://user-images.githubusercontent.com/91347931/189427836-938aa401-eb23-4fe6-8b91-ef0a203271a5.png)
