### ISSUE TITLE
Missplelling on the instructions? Source or Destination

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#279]
# Module: Module 02 - Implement Platform Protection
#### Step: 10. On the Add route blade, specify the following settings:

Description of issue
The instructions speaks about the **source**.
Address prefix **source** | IP Adresses
**Source** IP addresses/CIDR ranges | 0.0.0.0/0

But the user interface speaks about **destination**:
![kuva](https://user-images.githubusercontent.com/43988151/193446890-25362159-5fe0-4e10-8d19-195b7120736a.png)

Have a made a mistake on begin steps or, is this just misspelling issue on the instructions?

**Comment by serling1962** [comment]
Updated #### Task 3: Create a default route, 10. On the **Add route** blade, specify the following settings:  |Address prefix destination|**IP Address**|     |Destination IP addresses/CIDR ranges|**0.0.0.0/0**
