### ISSUE TITLE
Error on steps sequences

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#280]
# Module: Module 02 - Implement Platform Protection
#### Step: 11. Click Add to add the route.

Description of issue
This is described on the GitHub as Step 11. But on the student's material it is step 1:
![kuva](https://user-images.githubusercontent.com/43988151/193447553-5b75daea-6608-4291-98d1-e739156e66bb.png)

There seems to be other pages as well with the same issue, but need to start pick up them when notices next time. But this looks like a global issue, so if you find valid way to fix it, then all others gets fixed as well. Perhaps this have something to do with the code section before this step, and then the sequence of the bullets goes broken.

**Comment by serling1962** [comment]
GitHub reads correctly.

**Comment by Petri-X** [comment]
In my mind, I already clarified that. So there is an incident in the system itself.
