### ISSUE TITLE
Key Vault Access Policy GUI has been changed

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#289]
# Module: 3
#### Step: Multiple

Description of issue
The Key Vault access policy GUI has changed substantially in the Portal 

the lab steps do not match the new portal updates

Repro steps:

You will need to run through the labs as my students were saying that there were several locations where the lab instructions differ from the new portal changes.

**Comment by serling1962** [comment]
Please share a detailed list of the anomalies experiended.

Thanks.

**Comment by brentd09** [comment]
Azure has just changed the way that you submit a change to the Azure Key
Vault access policy. It is completely different than before (with good
reason) the previous method was crazy as you could see the change made but
if you did not click save the change was not made.Now you make the change
and its saved automatically.

Therefore the access policy section of the lab needs to be updated..

Thanks.

**Comment by serling1962** [comment]
Updated Azure Key Vault fields.
