### ISSUE TITLE
JIT Access intructions are not matching the Portal 

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#290]
# Module: 4
#### Step: many

Description of issue
Please rewrite the lab for the JIT access policy as much of this does not match the current portal screens

Repro steps:

1.
1.
1.

**Comment by serling1962** [comment]
The steps in Lab 14 are correct.  All tasks were tested as written.

Lab 13: Azure Monitor

Note:  Lab 13: Azure Monitor steps must be completed and preserved for Lab 14 and Lab 15.
***@***.***

***@***.***


Serling A. Davis

he/him
Sr Content Developer
L&R - GCL Product Management
Office: +1 214 4575779
***@***.******@***.***>

***@***.***
***@***.***

From: BrentD09 ***@***.***>
Sent: Wednesday, November 2, 2022 10:20 PM
To: MicrosoftLearning/AZ500-AzureSecurityTechnologies ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ500-AzureSecurityTechnologies] JIT Access intructions are not matching the Portal (Issue #290)

Module: 4
Lab/Demo: 14
Task: 3
Step: many

Description of issue
Please rewrite the lab for the JIT access policy as much of this does not match the current portal screens

Repro steps:

  1.
  2.
  3.

-

**Comment by serling1962** [comment]
JIT Access instructions are correct as written.
