### ISSUE TITLE
VM auto-shutdown causing issue in Lab 08

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#291]
# Module: 02
## Lab/Demo: 08

Description of issue
My class was running Lab 08 just before 7PM UTC, the template creates the two VMs with Auto-Shutdown at 7PM UTC causing the lab to fail. (Yes, they only needed to start the two VMs.) 
Should we remove the Auto-Shutdown from the template, or add a warning in the lab?  (Is this an issue with other labs?)

**Comment by serling1962** [comment]
Lab devs took a look through the templates and found the below reference timed shutdown:  

It appears that the learners performed the steps at the exact time as the shutdown, which caused the failure. We have not seen any reference on our side to something like this.

**Comment by ITBlandMCT** [comment]
Is there a reason for the auto-shutdown? If so, please add a warning to all labs, if not, why not remove it from the template?

Thanks

**Comment by serling1962** [comment]
Reviewing the needed updates tomorrow.
