### ISSUE TITLE
Instructions need updating Lab 13

### ISSUE THREAD

**Issue by jleblancxaf** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#295]
#### Step: 5

Description of issue

Step 5 mentions using the working version module 4.23.0 in the cloud session, when this is no longer needed.  
<img width="268" alt="Screenshot_1" src="https://user-images.githubusercontent.com/110999055/206473774-a499683d-a966-4c53-a0b9-3bd470e5b4dc.png">

**Comment by serling1962** [comment]
Az.Compute updated to 5.2.0.  Workaround instructions for 4.23.0 are no longer valid.
