### ISSUE TITLE
User and Sign-in risk policies have been migrated to conditional access policies

### ISSUE THREAD

**Issue by yashints** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#302]
# Module: 01
#### Task: 02, 03

The sign-in and user risk policies have been migrated to conditional access and users no longer can configure these in the identity protection. Are there any plans for updating these?

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/13609680/213022295-b3694b5c-951a-4503-a26a-0544fe20d43c.png)

**Comment by serling1962** [comment]
Updated.

**Comment by serling1962** [comment]
Instructions were updated.
