### ISSUE TITLE
VM shows up after waiting for 1 hour in Just-in-time VM access under not configured.

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#303]
# Module: 04
#### Step: 04

Description of issue
The VM created in Lab 13 shows up in JIT after waiting for about 1 hr in the not configured tab. However, it shows up in the Inventory after about 5 minutes.

![image](https://user-images.githubusercontent.com/98971092/219063649-ea1504f6-75fc-434b-a50e-f01f44f16d94.png)

![image](https://user-images.githubusercontent.com/98971092/219064397-835819d5-7dfc-45b4-92c2-b0ae3190754f.png)

Repro steps:

1. Perform all the prerequisite steps
2. See the result.

**Comment by serling1962** [comment]
This intermittent Azure issue has been relayed to Azure support for review and resolution.
