### ISSUE TITLE
Steps for enabling user risk policy and sign in risk policy are missing

### ISSUE THREAD

**Issue by christabelle** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#307]
# Module: 01
#### Task: 04

Step: 12

Description of issue

While testing this lab, my sign in was not blocked, because we did not enable Identity Protection before this step, we have only added the conditional policies.

https://microsoftlearning.github.io/AZ500-AzureSecurityTechnologies/Instructions/Labs/LAB_04_MFAConditionalAccessandAADIdentityProtection.html

I see in the Clean up resources, we are turning off Identity Protection for user and sign in risk, but we have not enabled it anywhere in the lab.
![image](https://user-images.githubusercontent.com/15212666/220365122-880aba1a-7721-4d6f-b3de-3d89c18a937d.png)

**Comment by serling1962** [comment]
In January, Identity Protection policies were migrated to Conditional Access. https://learn.microsoft.com/en-us/azure/active-directory/identity-protection/howto-identity-protection-configure-risk-policies#migrate-risk-policies-from-identity-protection-to-conditional-access
