### ISSUE TITLE
Lab 10: Key Vault (typo / no. of Key Permissions)

### ISSUE THREAD

**Issue by aniok-msft** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#315]
# Module: 09
#### Step: 09

Description of issue:  Lab instructions says "click Select all resulting in 12 selected permissions (Make sure the permissions for Rotation Policy Operations are unchecked)."
The number of Key Permissions are **9** selected permissions not **12**

See attached.
<img width="1071" alt="Lab 10 (AKV - key permissions)" src="https://user-images.githubusercontent.com/127273446/223609623-0d19b2f3-c523-4d9d-a473-a14915d6bb80.PNG">

Repro steps:

1.
1.
1.

**Comment by aniok-msft** [comment]
Suggest including in instruction "to check all the boxes under Cryptographic operations" for a total of **15 selected permissions**

Cryptographic permissions required for Task 05 (Create a table in the SQL Database and select data columns for encryption), Steps 14-17

**Comment by serling1962** [comment]
Update applied.
