### ISSUE TITLE
UI change broke lab 2

### ISSUE THREAD

**Issue by William-Storms** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#316]
# Module: 01
#### Step: 00

Description of issue:

Changes in the Portal UI broke the "guardrail" policies that prevent learners from generating extraneous resources.

In the last steps when the learner attempts to  create a VNET in UKSOUTH, they get an error message indicating that the lab policies deny the creation of Public IP addresses.

Repro steps:

1.
1.
1.

**Comment by serling1962** [comment]
Update: The LODS team reports the issue has been identified and remediated.
