### ISSUE TITLE
Cannot create the role assignment for ACR

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#318]
# Module: 00
#### Step: 1

Description of issue:

When running this command, 
ACRNAME=$(az acr list --resource-group AZ500LAB09 --query '[].{Name:name}' --output tsv)
az aks update -n MyKubernetesCluster -g AZ500LAB09 --attach-acr $ACRNAME

my students and I get the following error:

Could not create a role assignment for  ACR. Are you the Owner of this subscription?

Repro steps:

I have checked that the ACRNAME variable holds the correct value
I have added myself as an owner to the subscription

none of these steps make any difference, it still fails with the same error...

**Comment by serling1962** [comment]
We are posting the issue with Skillable.

**Comment by Universo-Ap00** [comment]
We have run many tests since Friday evening where we have not seen any errors, nor did any hint of an error to occur based out of any distinct regions. It appears to be an intermittent Azure bug/issue. Please try to run your lab again.
