### ISSUE TITLE
SQL encryption for the columns fails because of a lack of permissions in the key vault

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#319]
# Module: 00
#### Step: 9

Description of issue
The permissions are wrong in the lab leading to the SQL encrypted columns instructions later in the lab to fail

Repro steps:

This is the instruction that is wrong, this should read, Select all permissions for the Key permissions except Rotation Policy.
BTW it turns out to be more permissions than 9 its more like 15 or 16 in total. 

Key permissions | click Select all resulting in 9 selected permissions (Make sure the permissions for Rotation Policy Operations are unchecked)

When we tried this the SQL issue was resolved!

**Comment by serling1962** [comment]
Key permissions	click Select all resulting in 9 selected permissions (Make sure the permissions for Rotation Policy Operations are unchecked)

**Comment by brentd09** [comment]
9 permissions are not enough the others need to be selected as well, and yes you are correct that the rotation permissions need to be cleared. We tried the lab as written... the SQL encryption steps failed. we went back and added all of the permissions except for the rotation permissions and it then succeeded. I think you need to rethink the closing of this issue?

**Comment by serling1962** [comment]
Discard the errored post.  It reads as you detailed:

 |Key permissions|click **Select all** permissions (Make sure the permissions for **Rotation Policy Operations** are **unchecked**) |

**Comment by brentd09** [comment]
Actually its written in the lab as:
Key permissions | click Select all resulting in 9 selected permissions (Make sure the permissions for Rotation Policy Operations are unchecked)

**Comment by brentd09** [comment]
Thanks!
