### ISSUE TITLE
Module 8/Exercise 1/Task 1/Step 7

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#32]
# Module: 08
#### Step: 07

Following line needs to be modified as follows:

7.	Click **Review + Create** and then **Create**.

**Comment by adminazurestack** [comment]
the Azure Firewall not work. When is check access from IE in Srv-Work, all address are unavailable and DNS can resolve the name www.bing.com and www.microsoft.com
