### ISSUE TITLE
Activity Log not connecting to Sentinel

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#320]
# Module: 00
#### Step: 10

Description of issue
When trying to connect the activity log to Sentinel it appears to work however it never showed as connected. 

We noticed on the connector configuration page that it said that this has recently been updated to use diagnostic settings. 
 
We then checked the content hub and found that there was an "Azure Activity" solution listed here, when we installed it, the sentinel connector showed a connected state.

I hope this helps to find a solution for this lab

**Comment by serling1962** [comment]
No issues were encountered during testing.  Please retry the exercise.
