### ISSUE TITLE
Insuddicient Privileges to complete operation

### ISSUE THREAD

**Issue by henrikmai** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#322]
With Labhoster xtreme Labs the access rights are not enough to create user from LAB01/EX02/Task1
![image](https://user-images.githubusercontent.com/29449777/231074170-db2b7e42-5886-41df-96f8-c4447b97052d.png)

**Comment by serling1962** [comment]
No issues were encountered during testing.  Please retry the exercise.
