### ISSUE TITLE
Lab: 04, Exercise: 02, Task: 03, Steps: 05 and 07: 'User' role does not exist. Please remove the row from the table.

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#323]
# Lab: 04
#### Steps: 05 and 07

Description of issue:
There is no "User" role. Please remove this row from the table since it confuses the students thinking that exists, just like the Global Admin assigned two steps before. Also, having zero groups assigned does not add value since there is a message before saying "leave all others with their default values". Thanks!

**Comment by serling1962** [comment]
Edits applied as posted in Lab: 04 > Exercise: 02 > Task: 03 > Steps: 05 and 07
