### ISSUE TITLE
Virtual Machine not showing up in Just-in-time VM access under not configured.

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#324]
# Module: 04
#### Step: 04

Description of issue

The VM created in Lab 13 is not showing up in Just-in-time VM access any idea what I might be doing wrong here? I have also reported the issue before but the VM showed up in that case after waiting for about 1 hour. This time VM is not showing up at all even after waiting for about 2 and a half hours.

![image](https://user-images.githubusercontent.com/98971092/234907943-30d1a831-86fc-443c-9efe-22f0485d841f.png)

![image](https://user-images.githubusercontent.com/98971092/234907633-3638f5ee-f356-4887-9687-ba4641d1020c.png)

Link to old issue:
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/issues/303

Repro steps:

1. Perform all the prerequisite steps
1. See the result.

**Comment by serling1962** [comment]
The VM extended spawning time frame in Defender for Cloud is an embedded behavior.
