### ISSUE TITLE
Keyvault Access Policy, key permissions change.

### ISSUE THREAD

**Issue by ghoshdipanjan** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#326]
# Module: 00
#### Step: 09

Description of issue
In Keyvault access policy, Key permissions, the cryptographic Operations are separated now.  in the steps when we select All, it does not select those anymore.
Repro steps:

Configure from template : Key, Secret, & Certificate Management doesn't enable Cryptographic Operations. 
In Steps, Key Permissions says 'Select all' and then uncheck rotation policy operations.
I assumed I didn't need to enable cryptographic operations, but in Task 5 they are needed. Without sign operation the task will not be completed. We need to add a cryptographic keys too in the sentence.

**Comment by serling1962** [comment]
Key vault edit applied in Lab 10 > Task 01 > Step: 09.
