### ISSUE TITLE
Lab 12, Task 5, Step 9: Lab does not allow the creation of the file share in the storage account

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#339]
# Module: NA
#### Step: 9

Description of issue
The creation of this file share my-file-share is being blocked by a policy 

There is a work-around that will allow the file share to be created however, if you first untick the backup option in the backup tab, it then passes the validation step
Here are the screen shots that will help solve the issue:

![Screenshot 2023-07-06 115015](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/e94ddf37-1fcb-4dbf-8914-fb5ffbe4d761)

![Screenshot 2023-07-06 115033](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/ec7a0825-bb6b-4c7e-8155-a5cf7b0af579)

![Screenshot 2023-07-06 115102](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/9d430c9a-cd59-4657-86f0-36a9e1a608a6)

![Screenshot 2023-07-06 115137](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/4f5def74-1e90-4a06-9cd3-b8155347d053)

![Screenshot 2023-07-06 115211](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/f5435c6d-c8b2-43ea-ae1c-f20b79e07007)

**Comment by serling1962** [comment]
Edited applied and committed.  "untick the **Enable backup** option in the backup tab."
