### ISSUE TITLE
Lab 06: Implement Directory Synchronization

### ISSUE THREAD

**Issue by narenvivek** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#34]
# Module: AZ-500
#### Step: 05

Description of issue

Populating 'DNS Prefix', that is a mandatory parameter, seems to be missing in the instructions

<img width="559" alt="LAB_06_issue" src="https://user-images.githubusercontent.com/29542480/90089316-11abfd00-dcef-11ea-9792-3a5c11260cd8.PNG">

Repro steps:

1.
1.
1.

**Comment by azharkhuwaja** [comment]
**Task 1 Step 4** helps us to find the **DNS prefix** value.

Test-AzDnsAvailability -DomainNameLabel <custom-label> -Location '<location>'

**Comment by polichtm** [comment]
Step 4 states the following:

Setting | Value
-- | --
Subscription | the name of you Azure subscription
Resource group | click Create new and type the name AZ500LAB06
**Dns Prefix | the DNS hostname you identified in the previous task**
Location | the Azure region you identified in the previous task
Admin Username | Student
Admin Password | Pa55w.rd1234
Domain Name | adatum.com
VM Size | Standard_D2s_v3
rgds
Marcin
