### ISSUE TITLE
Lab 13 - Not getting expected result in guide 

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#358]
#### Step: 2

Description of issue
When selecting "Azure Virtual machines (VMs)" under the "Connect a Data Source" section (screenshot below), I am not taken to a list of virtual machines. You are prompted to create a data collection rule. The screenshot shows where you are taken instead, when clicking "Azure Virtual machines (VMs)".

Repro steps:

1. In the Azure portal, navigate back to the Log Analytics workspaces blade, and, in the list of workspaces, click the entry representing the workspace you created in the previous task.

2. On the Log Analytics workspace blade, on the Overview page, in the Connect a Data Source section, click the Azure Virtual machines (VMs) entry.

3. In the list of virtual machines, locate the entry representing the Azure VM myVM you deployed in the first task of this exercise and note that it is listed as Not connected.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/114931569/69ea887d-2930-458e-82ea-58d809645b5f)

**Comment by serling1962** [comment]
The exercise was edited to reflect updated methods in the Azure portal.
