### ISSUE TITLE
New Lab 13 not complete?

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#361]
# Module: 04
### Task: 04

Description of issue
Task 4 appears to just be a copy of Task 3 - is something missing? (Possibly a copy/paste error?--been there, done that!)

**Comment by serling1962** [comment]
The #13 was changed to reflect the latest MSFT documented procedure for collecting and analyzing resource logs from an Azure resource.
