### ISSUE TITLE
Lab 10: Az.KeyVault 4.10.2 Install-Module workaround requires Cloud Shell close/reopen

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#366]
- Module 03: Secure Data and Applications
- Lab 10: Key Vault (Implementing Secure Data by setting up Always Encrypted)
- Exercise 3: Configure an Azure SQL database and a data-driven application
- Task 2: Create a policy allowing the application access to the Key Vault

A followup to #359:

An addendum to the initial report is that the Cloud Shell session must be closed and reopened after running the `Install-Module` command, otherwise `Az.KeyVault` 4.10.1 will still be loaded and the `Set-AZKeyVaultAccessPolicy` command will still fail. There may also be a PowerShell command which can successfully reload the new version of the module without a relaunch, but I wasn't able to discover one in attempts so far.

If an instruction to relaunch the Cloud Shell session can be placed after the Install-Module command, that should allow this workaround to be effective. The `Install-Module` command should be positioned before the steps in this task that set PowerShell variables, so that the variables are not cleared when the session is relaunched.

**Comment by ITBlandMCT** [comment]
It is also possible to use the Cloud Shell Restart button and then go back and re-do the previous steps to populate the variables.

**Comment by serling1962** [comment]
Step 6 was added as a short term "fix" until the next Az release.

Task 2: Create a policy allowing the application access to the Key Vault.
In this task, you will grant the newly registered app permissions to access secrets stored in the Key Vault.

In the Azure portal, open a PowerShell session in the Cloud Shell pane.

Ensure PowerShell is selected in the upper-left drop-down menu of the Cloud Shell pane.

4. In the PowerShell session within the Cloud Shell pane, run the following to create a variable storing the Application (client) ID you recorded in the previous task (replace the <Azure_AD_Application_ID> placeholder with the value of the Application (client) ID):

$applicationId = '<Azure_AD_Application_ID>'
In the PowerShell session within the Cloud Shell pane, run the following to create a variable storing the Key Vault name.

$kvName = (Get-AzKeyVault -ResourceGroupName 'AZ500LAB10').VaultName

$kvName

5. In the PowerShell session within the Cloud Shell pane, run the following to update the Az.KeyVault module to the latest available version.

Install-Module Az.KeyVault -Repository PSGallery -Force -AllowClobber

6. Relaunch the Cloud Shell session.
