### ISSUE TITLE
Instructions/Labs/LAB_04_MFAConditionalAccessandAADIdentityProtection.md

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#372]
# Module: 01
#### Step: 05

Premium P2 Free Trial Activation error: OrderFailedRiskManagementCheck

Follow lab instructions exactly to get error on Lab 4 Ex 2 Task 2 Step 5

{"errorCode":"OrderFailedRiskManagementCheck","localizedErrorDetails":{"orderFailedRiskManagementCheck":"Request failed fraud check: ErrorCode:6118; Message:Order failed Risk Management Check"},"operationResults":null,"timeStampUtc":"2023-09-11T18:18:18.1535358Z","clientRequestId":"","internalTransactionId":"","tenantId":null,"userObjectId":"","exceptionType":"FaultException<AccessDeniedFault>"}

**Comment by Danoz0r** [comment]
Same issue.

**Comment by serling1962** [comment]
The Azure AD Premium P2 trail license was successfully activated applying the following task and steps.

Task 2: Activate Azure AD Premium P2 trial
In this task, you will sign up for the Azure AD Premium P2 free trial.

In the Azure portal, in the toolbar, click the Directory + subscription icon, located to the right of the Cloud Shell icon.

In the Directory + subscription blade, click the newly created tenant AdatumLab500-04 and click the Switch button to set it as the current directory.

Note: You may need to refresh the browser window if the AdatumLab500-04 entry does not appear in the Directory + subscription filter list.

In the Azure portal, in the Search resources, services, and docs text box at the top of the Azure portal page, type Azure Active Directory and press the Enter key. On the AdatumLab500-04 blade, in the Manage section, click Licenses.

On the Licenses | Overview blade, in the Manage section, click All products and then click + Try / Buy.

On the Activate blade, in the Azure AD Premium P2 section, click Free Trial and then click Activate.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/91347931/f9fcd66f-e75e-4044-8e24-9397b41d3ec1)

**Comment by Danoz0r** [comment]
I tried with multiple accounts. Get the same error on all of them.
<img width="396" alt="image" src="https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/98827368/8659630a-2935-4882-9e0e-9f2a2b2acf7b">
