### ISSUE TITLE
Lab 15 - Upgrading Defender reverts back

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#378]
### Step: 03

Description of issue: The step initially allows you to upgrade Defender. However, when you try to save the changes, the upgrade reverts back.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/2e46db8f-e961-4b38-b7dd-ccba81bfb233)

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/497307e0-2f9a-4369-94aa-522079782b9f)

**Comment by serling1962** [comment]
The first requirement is to upgrade your subscription. See example at this link: https://microsoftlearning.github.io/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/Instructions/Labs/LAB_03a_Enable%20Defender%20for%20Cloud%20on%20your%20Azure%20subscription.html
