### ISSUE TITLE
Vnet deployment

### ISSUE THREAD

**Issue by SQLtattoo** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#379]
# Module: 01
#### Step: 02

Description of issue
Some users although have relaunched the labs more than a couple of times, they still see the new experience with "Security" before 
"IP Addresses", so we need to fix the instruction with the new UI.

Repro steps:
follow instructions on Task 2 step 1 and you will see it.

**Comment by serling1962** [comment]
Issue not found. Module 01 is Manage Identity and Access > Lab 01: Role-Based Access Control > Task 02 reads: Use the Azure portal to create a Senior Admins group and add the user account of Joseph Price to the group.
