### ISSUE TITLE
Wording a bit confusing

### ISSUE THREAD

**Issue by daracloud** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#381]
#LearningPath: 2
#### Step: 3 and 4

Description of issue Instead of Instruction says **On the myVMWeb blade, in the Settings section, click Networking and then, on the myVMWeb | Networking blade, click the Application security groups tab.

Click Configure the application security groups, in the Application security group drop-down list, select myAsgWebServers, and then click Save.**

Repro steps:
There is no drop-down list to select from. The task should have been worded as follows.
- Under **Networking** click on **Application security groups**
- Click **Add application security groups**
- Add vm to the Application security group

Task 04
Step 5 and 6
Run command is not under Operations section but under Payload section.
1.
1.
1.

**Comment by serling1962** [comment]
Corrections applied.
