### ISSUE TITLE
LAB_04_MFAConditionalAccessandAADIdentityProtection.md - AAD renamed Entra ID

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#382]
# Module: 
## Lab/Demo: 04
Exercise 1
#### Step: 01, 03

Description of issue
Text says 'Azure Active Directory', Azure UI seems to now have been updated to be called 'Microsoft Entra ID' now so this step should be updated.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/49700217/83407a6d-d8ca-4e98-b42b-cfdf08aaaa1f)

Also in Task 2, Step 3 AAD is referenced, and lastly - the licenses take on the Entra naming convention as well and should be updated in the instructions:
![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/49700217/72a15500-856f-46ee-ae37-e12c4e939ec6)

**Comment by serling1962** [comment]
Completed.
