### ISSUE TITLE
NO CORRESPONDING AZ500LAB09-vnet WITHIN THE AZ500LAB09

### ISSUE THREAD

**Issue by ubiquituz1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#383]
# Module: AZ500-AzureSecurityTechnologies
#### Step: 2

Description of issue
AZ500LAB09-vnet was not avalaible and I had to manually create it
Repro steps:

1.
1.
1.

**Comment by serling1962** [comment]
Issue not found.
