### ISSUE TITLE
az500lab12 rg will not delete due to auto-created lock by the fileshare azure backup protection

### ISSUE THREAD

**Issue by ubiquituz1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#384]
# Module: Remove-AzResourceGroup -Name "AZ500LAB12" -Force -AsJob
#### Step: 00

Description of issue
az500lab12 rg will not delete due to auto-created lock by the fileshare azure backup protection
Repro steps:

1.
1.
1.

**Comment by serling1962** [comment]
Command removed.
