### ISSUE TITLE
Entra ID Connect has wrong instructions 

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#389]
![EntraIDSyncLabIssue](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/4eba46d6-577e-45a3-be3b-25132571a863)
# Module: 00
#### Step: 05

Description of issue

It appears that a search and replace has been done across the entire instructions and this has resulted in this being added to the lab instructions: **Microsoft Entra ID Administrative Center**. 

This should read: **Active Directory Administrative Center**

Please edit these references and change them back to their proper name. 

Other than this issue the lab now works perfectly.

**Comment by brentd09** [comment]
![Uploading EntraIDSyncLabIssue.png…]()

**Comment by serling1962** [comment]
Azure AD admin center Azure Active Directory admin center > Replaced with Microsoft Entra admin center. Source: https://learn.microsoft.com/en-us/entra/fundamentals/new-name

**Comment by brentd09** [comment]
You have missed the point of the issue. the lab is talking about the ON-PREM Active Directory Administrative Center but your lab is referring to it as the Microsoft Entra ID Administrative Center.

Please change the occurrences of  **Microsoft Entra ID Administrative Center** to **Active Directory Administrative Center**...

I have even included the picture so that it cannot be mistaken. We are not talking about a cloud tool here we are talking about the on-prem ADDS tool. Can you please fix this so that the name matches the picture I sent with the issue..
