### ISSUE TITLE
Step  11  is redundant in PIM Lab Exercise 01- Task 01

### ISSUE THREAD

**Issue by Sheshgiriv** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#39]
# Module: AZ500-AzureSecurityTechnologies
#### Step: 11

Description of issue
     Step 11 is redundant as the as aaduser2 is already visible in the assignments blade after completion of Step 10. 

Repro steps:

1. Sign-in to the Azure portal https://portal.azure.com/.

Note: Ensure that you are signed-in to the AdatumLab500-04 Azure AD tenant. You can use the Directory + subscription filter to switch between Azure AD tenants. Ensure you are signed in as a user with the Global Administrator role.

2.In the Azure portal, in the Search resources, services, and docs text box at the top of the Azure portal page, type Azure AD Privileged Identity Management and press the Enter key.

3.On the Azure AD Privileged Identity Management blade, in the Manage section, click Azure AD roles.

4.On the AdatumLab500-04 | Quick start blade, in the Manage section, click Roles.

5.On the AdatumLab500-04 | Roles blade, click + Add assignments.

6.On the Add assignments blade, in the Select a role drop-down, select Billing Administrator.

7. Click the No member selected link, on the Select a member blade, click aaduser2, and then click Select.

8. Back on the Add assignments blade, click Next.

9. Ensure the Assignment type is set to Eligible, review the eligible duration settings, and click Assign.

10. Back on the AdatumLab500-04 | Roles blade, in the Manage section, click Assignments.

11. On the AdatumLab500-04 | Assignments blade, click Member filter, on the Select a member blade, click aaduser2, and click Select.

Back on the AdatumLab500-04 | Assignments blade, note the tabs for Eligible assignments, Active assignments, and Expired assignments.

Verify on the Eligible assignments tab that aaduser2 is shown as a Billing administrator.

**Comment by polichtm** [comment]
updated
