### ISSUE TITLE
Missing steps from Monitor lab

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#390]
# Module: 00
#### Step: 05

Description of issue

The lab is missing the steps to select the VM and then click apply

![SNAG--Thu 9-Nov-2023-9 52 43 AM](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/18732050/7f545986-d518-408d-8c3d-a2ca346860c5)

**Comment by serling1962** [comment]
The step referenced in the issue is neither required nor visible in the Azure dashboard, possibly due to ongoing A/B testing by the Azure team, which may have led to changes in some functions.
