### ISSUE TITLE
Lab 11 fails when adding the old Az.Compute mudule

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#391]
# Module: 00
#### Step: 00

Description of issue
The lab instructs students to install the old Az.Compute Module in the Skillable lab instructions.

Once the old 4.23.0 module is loaded into the lab many conflicts occur making the lab impossible to complete. This is a prereq lab for 12 and 13 so none of these can run.

We decided to create the VM manually and NOT install the old az.Compute Module and now everything seems to be working.

I am not sure if this is a Microsoft or Skillable issue..

**Comment by brentd09** [comment]
We found a workaround that will allow the lab to work as written without installing the 4.23.0 version of the az.compute module.

if you run the Register-AzProviderFeature this will enable the providerfeature that is needed to run the New-AzVm command.

The exact command is Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute"

**Comment by markingram1** [comment]
Without installing the old Az.Compute Module, despite error messages in PowerShell, the resources do, in fact, get created.
