### ISSUE TITLE
Cannot find the "Microsoft Azure Management" in the Conditional Access

### ISSUE THREAD

**Issue by Philipnyeung** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#392]
# Module: 01
## Lab/Demo: 02
Lab 02: MFA, and Conditional Access
Exercise 3: Implement Microsoft Entra ID Conditional Access Policies

### Task: 01
Task 1 - Configure a conditional access policy.

#### Step: 05
5. On the New blade, configure the following settings:
Under Target resources, click No target resources selected, click Select apps, under Select, click None. On the Select blade, select the checkbox for Microsoft Azure Management and click Select.
Description of issue

Repro steps:

Cannot find the Microsoft Azure Management in the Conditional Access

**Comment by serling1962** [comment]
**Note:** The task of creating a conditional access policy will be removed from the lab instructions due to the requirement of signing into the Microsoft Enterprise Admin Center as a Conditional Access Administrator to create the policy.
