### ISSUE TITLE
Suspicious activity detected message did not displayed

### ISSUE THREAD

**Issue by Philipnyeung** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#393]
#### Step: 13 In the ToR browser, select the back arrow to sign in as aaduser1 account you created and configured for multi-factor authentication earlier in this lab. "This time, you will be presented with the Suspicious activity detected message"

Description of issue

 Suspicious activity detected message did not displayed.

**Comment by serling1962** [comment]
Could not reproduce the error.
