### ISSUE TITLE
Lab 13 Exercise 1: Implement Microsoft Sentinel

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#398]
# Module: 13 Exercise 1: Implement Microsoft Sentinel
#### Step: 12

Give error:
I am currently testing these labs on lab 11 to onward lab 13 but when we reach at lab 13 Task 02 step 12 its give me the error that I show in the screen shot. Kindly tell me what's need required?

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/142339674/1c88c9ed-443d-4c39-b173-cd79442aecd3)

**Comment by serling1962** [comment]
Reviewing the error message.
