### ISSUE TITLE
Lab 02 Microsoft Azure Management renamed to Windows Azure Service Management API

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#399]
### Step: 05

Description of issue
Microsoft Azure Management [has been renamed to Windows Azure Service Management API.](https://learn.microsoft.com/en-us/answers/questions/1409393/microsoft-azure-management-not-appearing-in-list-o). I've confirmed Microsoft Azure Management does not show when searching for it under Cloud Apps, but Windows Azure Service Management API does and contains the previous tools and functions of Azure Management [p1]. Some classes have reported confusion about the rename.

[p1]

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/94069201/226f1629-4a33-4a39-865a-cc5b299cda52)

**Comment by serling1962** [comment]
Windows Azure Service Management API edit applied.
