### ISSUE TITLE
Microsoft Entra ID Disabled - Immediate Content Update Needed

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#400]
The Microsoft Entra ID under the tenant type is disabled, causing issues for four crucial modules. We urge you to promptly update the content.

**Comment by dave-007** [comment]
I recieved a Skillable email Dec 15 that noted these labs are down, which others?

AZ-500T00-A – Microsoft Azure Security Technologies

**_Lab 2 & 3_** – MFA and Conditional Access, Azure AD Privileged Identity Management
**_Lab 4_** – Implement Directory Synchronization

**Comment by serling1962** [comment]
Labs 2 and 3 are paused until a viable or alternative solution regarding the latest Azure modifications and licensing requirements is resolved. Lab 4 is effectively retired. Modifications to reflect the latest changes in these labs are in process.
