### ISSUE TITLE
SSMS missing in Lab 07 Key Vault (Implementing Secure Data by setting up Always Encrypted)

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#403]
# Module: 04
#### Step: 06

Description of issue
SQL Server Mgmt Studio is not present on the VM created in the lab; this could be an issue with the lab provider (Skillable), or the image in the Marketplace may have changed. Workaround is to download and install SSMS from the Internet.

From the template in Allfiles:
    "imagePublisher": "MicrosoftVisualStudio",
    "imageOffer": "VisualStudio2019latest",
    "imageSku": "vs-2019-comm-latest-ws2019",

**Comment by serling1962** [comment]
The workaround is as follows:

6. Install [SQL Server Management Studio](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?preserve-view=true&view=sql-server-2017) on **az500-10-vm1.** Azure VM.
 
7. Open **SQL Server Management Studio.**
