### ISSUE TITLE
Lab 01 Issues

### ISSUE THREAD

**Issue by RSim92** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#408]
# Module: 01
#### Step: 01

Powershell commands out of sequence

New-MgGroupMemeber - spelling error, extra E

Incorrect syntax
-MailEnabled $false -SecurityEnabled $true
Should be:
-MailEnabled:$false -SecurityEnabled:$true

**Comment by serling1962** [comment]
Edited spelling entry and exercise step sequence.
