### ISSUE TITLE
Module 01 Lab 01 Exercise 02

### ISSUE THREAD

**Issue by rtrader58** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#409]
# Module: 01
#### Step: 00

Description of issue

The lab calls for use of the  Azure Cloud Shell, there is no subscription provided by the ALH provider.  So there is no way to launch the Cloud Shell as it requires a Storage Account.  Recommend changing the steps to install PowerShell locally as is the Azure CLI is in Exercise 03.

**Comment by L4bguru** [comment]
This lab in its entirety is likely to fail in all ALH platforms.

There's no way lab hosters will grant students permissions to be able to create users in their tenants / subscriptions.. author needs to re-think the lab steps.

**Comment by rtrader58** [comment]
The ALH GoDeploy.IT added a work around, they modified the steps to have the students install the PowerShell Module locally and now the exercise works.

**Comment by serling1962** [comment]
As written, the requirement for Lab 01 > Exercise 2 Cloud Shell > PowerShell is not the result of a recent edit or update; it has been utilized by ALH's since at least 2021.
