### ISSUE TITLE
Instructed Option Selection Missing In Lab 06 - Exercise 1 - Task 2 - Step 5

### ISSUE THREAD

**Issue by SkillableKA** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#411]
Lab 06 - Service Endpoints and Securing Storage - Exercise 1 - Task 2 - Step 5.) On the Add subnet blade, specify the following settings (leave others with their default values):
 
The Service Endpoints drop down does not allow the user to select Microsoft.Storage as indicated in the instructions. The only available option is the default of 'None'.

This causes no other issues with the lab, as I left the default 'None' and completed the lab successfully, but has caused some lab users to get stuck at this point assuming it's a requirement.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/169093291/a2f38753-c9ca-4861-9994-3014f225914c)

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/169093291/ed4a2b16-9dfe-4c95-a721-3acb942218fb)

**Comment by serling1962** [comment]
Step updated to reflect the environment setup.
