### ISSUE TITLE
PowerShell command is missing a needed parameter

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#416]
# Module: 00
#### Step: 03

Description of issue
The PowerShell command to create the KV is wrong to enable policy based access to the data plane 

This is the current PS commands

```
$kvName = 'az500kv' + $(Get-Random)
$location = (Get-AzResourceGroup -ResourceGroupName 'AZ500LAB10-lod41132372').Location
New-AzKeyVault -VaultName $kvName -ResourceGroupName 'AZ500LAB10-lod41132372' -Location $location
```

However, this will cause the next part of the lab to fail as this has created the Key Vault with RBAC for the Data Plane and because of cloud slicing we can not change it after the creation

The PowerShell command should be changed to the following:

```
New-AzKeyVault -VaultName $kvName -ResourceGroupName 'AZ500LAB10-lod41132372' -Location $location -DisableRbacAuthorization
```

This will create the KV and switch the data plane access to policy based

**Comment by serling1962** [comment]
The edit was applied as noted.
