### ISSUE TITLE
M02 Lab02 Wrong section name in instructions

### ISSUE THREAD

**Issue by 1amitn** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#417]
# Module: 02
#### Step: 05

Description of issue
Wrong section name: "Payload" instead of "Operations"

Repro steps:
Exercise 2: Deploy virtual machines and test network filters
Task 4: Test the network traffic filtering
Step 5: "On the myVMWeb blade, in the **Payload** section, click Run command and then click RunPowerShellScript."

Please find image below:
![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/124911652/299d9061-dd43-4927-a7f3-b5a1769cab6b)

**Comment by serling1962** [comment]
Edit applied.
