### ISSUE TITLE
Error - Lab 01: Role-Based Access Control

### ISSUE THREAD

**Issue by adolfoguz** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#418]
https://microsoftlearning.github.io/AZ500-AzureSecurityTechnologies/Instructions/Labs/LAB_01_RBAC.html
Lab 01: Role-Based Access Control
Exercise 2: Create a Junior Admins group containing the user account of Isabel Garcia as its member.
Task 1: Use PowerShell to create a user account for Isabel Garcia.
Step Number:  5, 6 and Next…

When performing step 5 this error appears and then the following steps of the lab do not work well.

Error: Need admin approval
          Authentication cannot be performed and it is not possible to continue with the rest of the exercises.

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/156321496/8efb6048-c649-4733-95ab-33d4fc225120)

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/assets/156321496/76a4be61-9aa6-406e-bc4a-7a8f4c9a6eba)

Thank you

**Comment by serling1962** [comment]
Unable to reproduce the issue.
