### ISSUE TITLE
Lab3 - Task 6: The Networking menu is no longer under the Settings menu

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#424]
# Module: 00
#### Step: 3

Description of issue
Change of location for the networking:
Networking is no longer under the settings node, it is a separate menu 
Problem in bold below

Repro steps:

Task 6: Configure the virtual machine DNS servers
In this task, you will configure the primary and secondary DNS addresses for the virtual machine. This is not a firewall requirement.

In the Azure portal, navigate back to the AZ500LAB08 resource group.

On the AZ500LAB08 blade, in the list of resources, click the Srv-Work virtual machine.

On the Srv-Work blade, in the **Settings section, click Networking.**

**Comment by serling1962** [comment]
Edit applied. 

Thanks.
