### ISSUE TITLE
Use of deprecated Powershell Module

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#425]
# Module: 01
## Exercise 2

AzureAD Module is deprecated since April 2024 and should not be used anymore!
https://techcommunity.microsoft.com/t5/microsoft-entra-blog/important-azure-ad-graph-retirement-and-powershell-module/ba-p/3848270

Why do you teach content to the students that's no longer valid???

**Comment by serling1962** [comment]
GitHub lab instructions are aligned with the authorized learning hosting providers environment.

**Comment by serling1962** [comment]
AZ 500 lab exercises are aligned with Skillables hosted environment.
