### ISSUE TITLE
LAB 9: Configure Microsoft Defender for cloud

### ISSUE THREAD

**Issue by Joe6001** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#430]
![2](https://github.com/user-attachments/assets/23f02340-3006-48ef-bb5f-27f05d7e6a17)

The above instructions does not match the results am getting on my Azure 

![1](https://github.com/user-attachments/assets/8a37d157-c6d0-477b-9c04-a8a90124f7a2)

How do I fix this

**Comment by wbpluto** [comment]
Confirmed. The current portal interface has been updated and no longer matches the current instructions

**Comment by serling1962** [comment]
Updated Microsoft Defender for Cloud onboarding instructions.
