### ISSUE TITLE
Not able to set 'Access Management for Azure resources' property 

### ISSUE THREAD

**Issue by Sheshgiriv** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#46]
# Module: Module 01 - Manage Identity and Access
#### Step: 14

Description of issue
     14. Navigate to the AdatumSync - Overview blade of the Azure AD tenant, click Delete tenant, on the Delete directory 'AdatumSync' blade, click the Get permission to delete Azure resources link, on the Properties blade of Azure Active Directory, set Access management for Azure resources to Yes and click Save

In the above step the property 'Access Management for Azure resources' never gets set to Yes , even the change is made and saved successfully on relogin the property value is set to No and this is inturn stopping the directory dle

**Comment by polichtm** [comment]
pls follow https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto
rgds
Marcin
