### ISSUE TITLE
Typo in Lab 04

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#49]
# Module: 01
#### Step: 00

Description of issue
The note at the beginning of task 4 references "Exercise 0" but there is no exercise 0. It's meant to refer to "Exercise 1"

Before you start this task, ensure that the template deployment you started in **Exercise 0** has completed. The deployment includes an Azure VM named az500-04-vm1.

**Comment by polichtm** [comment]
updated
