### ISSUE TITLE
Request the user to login to the Azure portal using the VM

### ISSUE THREAD

**Issue by Sheshgiriv** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#51]
Module: AZ500-AzureSecurityTechnologies
Lab/Demo: LAB_10_KeyVaultImplementingSecureDatabysettingupAlwaysEncrypted
Exercise 2: Create an application to demonstrate using the key vault for encryption
Task 4: Create a table in the SQL Database and select data columns for encryption
Step 2: On the Firewall settings blade, click + Add client IP, next click Save and then click OK.

Description of issue
Better to request the user to login to the azure portal using the VM which is created for SSMS and Visual Studio components as the SQL DB connection is required for these components. The workaround for configuring the correct Client IP becomes cumbersome if it is not configured correctly in the initial step.

**Comment by polichtm** [comment]
updated
rgds
Marcin
