### ISSUE TITLE
Task 5: Step 4 is redundant

### ISSUE THREAD

**Issue by Sheshgiriv** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#52]
Module 04 - Manage security operations
 Lab/Demo: LAB_13_Azure Monitor
Task 5: View and query collected data
 Step: 4 On the Example queries pane, click Virtual machine

Description of issue
    After clicking the get started button, the predefined queries are displayed directly and there is no virtual machine icon displayed.

**Comment by polichtm** [comment]
Just to confirm - are you not seeing the "Virtual machine" category in the list of queries - as per the screenshot below?
![image](https://user-images.githubusercontent.com/10284906/94993351-65ec9400-055e-11eb-9959-d8fdc7051ea0.png)
rgds
Marcin

**Comment by Sheshgiriv** [comment]
This is how the screen appears for me. The `All Queries` blade doesn't further drill down like the way it has  in your screenshot.

![LogAnalytics_ScreenShot](https://user-images.githubusercontent.com/52245326/94997057-2bb6dd00-05c6-11eb-8eaf-062ed38a414e.png)

**Comment by polichtm** [comment]
That's because you have the Resource Type filter set to Log Analytics workspaces
rgds
Marcin

**Comment by Sheshgiriv** [comment]
Looks like an oversight from my end , thanks for helping out. I will be closing the issue now.

**Comment by polichtm** [comment]
np - you're welcome
rgds
Marcin
