### ISSUE TITLE
Lab Demo Recording video

### ISSUE THREAD

**Issue by cheahengsoon** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#56]
Hi Team,

The Lab Demo Recording video for AZ-500 still does not updated since 2 months ago.

[AZ-500 Lab Demo Recording](https://github.com/MicrosoftLearning/Lab-Demo-Recordings/blob/master/AZ-500.md)

any ideas when will release the Lab Demo Recording videos?

Thank you.

**Comment by staleycyn** [comment]
There are no plans to record Lab videos for this course.
