### ISSUE TITLE
unable to load this json file for creation of azure key vault

### ISSUE THREAD

**Issue by SaMolPP** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#57]
# Module: 00
#### Step: 00

Description of issue
am unable to load this json file for creation of azure key vault on this step 
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/blob/master/Instructions/Labs/LAB_10_KeyVaultImplementingSecureDatabysettingupAlwaysEncrypted.md

"On the Edit template blade, click Load file, locate the \Allfiles\Labs\10\az-500-10_azuredeploy.json file and click Open."
 this gave me , an error  while cliked on the save button :
"

Error parsing template. Please ensure template is valid JSON. Invalid symbol at position 5. Invalid symbol at position 15. Invalid symbol at position 21. Invalid symbol at position 27. Invalid symbol at position 36. Invalid symbol at position 40. Invalid symbol at position 51. Invalid symbol at position 57. End of file expected at position 65. 
"

below is the first section of the json file:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

![azureeployjsonfile](https://user-images.githubusercontent.com/6067107/95381827-5aa2bb00-0906-11eb-99a2-6ac8aef27d91.PNG)

this is the json file, i wanna upload and save it.  This gave me an error.
please help, how to resolve this and proceed with creating a azure key vault

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Pls follow up with your MCT
rgds
Marcin

**Comment by polichtm** [comment]
If you still haven't managed to get this resolved, pls post the content of the template you are trying to use
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
