### ISSUE TITLE
Module 1: Lab 3: Resource Manager Locks

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#80]
Module   1: Lab 3: Resource Manager Locks
--

Ex 1 Task 1 Step   2: Cloudshell storage may already exist from previous lab. Continue.
Ex 1   Task 5 Step 4 and 5: Error message now displayed by Azure portal before   proceeding.

**Comment by polichtm** [comment]
updated
