### ISSUE TITLE
Module 1: Lab 4: MFA, Conditional Access and AAD Identity Protection

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#81]
Module   1: Lab 4: MFA, Conditional Access and AAD Identity Protection
--

Ex 2   Task 3 Step 3: Need to click Create to create user.
Ex 2   Task 3 Step 5: Need to click Create to create user.
Ex 2   Task 4 Step 3: the new users may be set to United States already.
Ex 2   Task 4 Step 6: "Users and Groups" should be "Users"
Ex 2   Task 5 Step 8: "Enforced" should be "Enforce"
Ex 2   Task 6 Step 4: May have to click "I want to setup a   different method" and then select Phone and then Confirm.
Ex 2   Task 6 Step 7: May have to restart the Azure portal in the InPrivate browser   window first and then login again as aaduser1
Ex 4   Task 5: aaduser3 only appears under Risk detections report

**Comment by polichtm** [comment]
updated
