### ISSUE TITLE
Module 1: Lab 5 - Azure AD Privileged Identity Management 

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#82]
Module   1: Lab 5 - Azure AD Privileged Identity Management
--

Ex 1   Task 3 Step 7: Permanently eligible option not available. Default is 1 year. Continue.
Ex 3   Task 2 Step 4: May have to select Azure AD Roles to see the Overview page.

**Comment by polichtm** [comment]
updated
