### ISSUE TITLE
Module 2: Lab 7: Network Security Groups and Application Security Groups 

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#85]
Module   2: Lab 7: Network Security Groups and Application Security Groups
--

Ex 2   Task 1 Step 2: "On the Virtual machines blade, click + Add." should   be "On the Virtual machines blade, click + Add, and then select Virtual   machine.
Ex 2   Task 1 Step 3: "	Windows Server 2019 Datacenter" should be   "	Windows Server 2019 Datacenter Gen 1"
Ex 2   Task 2 Step 1: "On the Virtual machines blade, click + Add." should   be "On the Virtual machines blade, click + Add, and then select Virtual   machine.
Ex 2   Task 2 Step 2: "	Windows Server 2019 Datacenter" should be   "	Windows Server 2019 Datacenter Gen 1"

**Comment by polichtm** [comment]
updated
