### ISSUE TITLE
Module 3: Lab 12: Service Endpoints and Securing Storage

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#88]
Module   3: Lab 12: Service Endpoints and Securing Storage
--

Ex 1   Task 3 Step 11: Need to click Add to add the second OutBound Rule.
Ex 1   Task 5 Step 2: "On the Virtual machines blade, click + Add." should   be "On the Virtual machines blade, click + Add, and then select Virtual   machine
Ex 1   Task 5 Step 3: "Windows Server 2019 Datacenter" should be   "	Windows Server 2019 Datacenter - Gen 1"
Ex 1   Task 5 Step 6: Boot diagnostics set to "Enable with managed storage   account (Recommended)"
Ex 1   Task 5 Step 8: "On the Virtual machines blade, click + Add." should   be "On the Virtual machines blade, click + Add, and then select Virtual   machine
Ex 1   Task 5 Step 9: "Windows Server 2019 Datacenter" should be   "	Windows Server 2019 Datacenter - Gen 1"
Ex 1   Task 5 Step 12: Boot diagnostics set to "Enable with managed storage   account (Recommended)"

**Comment by polichtm** [comment]
updated
