### ISSUE TITLE
Module 4: Lab 13: Azure Monitor 

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#89]
Module   4: Lab 13: Azure Monitor
--

Ex 1   Task 5 Step 4: The default is to show the Resource Type : Log Analytics.   Click the X to show all the resource types on the left, then scroll down, and   then select Virtual machine to show example queries for that resource type.

**Comment by polichtm** [comment]
updated
