### ISSUE TITLE
Module 4: Lab 14: Azure Security Center

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#90]
Module   4: Lab 14: Azure Security Center
--

Ex 1   Task 1 Step 4: "On the Security Center \| Getting started blade, click   Pricing & settings." should be "On the Security Center resource   menu, select Pricing & settings."
Ex 1   Task 1 Step 7: "On the Settings blade, click Data Collection."   should be "On the Settings blade, click Auto Provisioning."
Ex 1   Task 1 Step 8: "On the Settings \| Data Collection blade, set Auto   provisioning to On." should be "On the Settings \| Auto provisioning   blade, set Log Analytics agent for Azure VMs to On and then select Edit   Configuration."
Ex 1   Task 1 Step 9: "Use another workspace" should be "Connect   Azure VMs to a different workspace"
Ex 1   Task 1 Step 9: at end add "then select Apply, and when prompted, select   Existing and new VMs, and then select Apply again"
Ex 1   Task 1 Step 10: "On the Settings \| Data Collection blade, click   Save." should be "On the Settings \| Auto provisioning blade, click   Save."
Ex 1   Task 2 Step 2: "On the Security Center \| Overview blade, in the POLICY   & COMPLIANCE section, click Secure Score." should be "On the   Security Center resource menu, in the Cloud security section, click Secure   Score."
Ex 1   Task 2 Step 3: "On the Cloud Security \| Secure Score blade, click on   your subscription." should be "On the Secure Score blade, scroll   down and click on your subscription."
Ex 1   Task 2 Step 5: May have to wait for myVM to appear in the list. Try refresh   of browser.
Ex 1   Task 3 Step 2: May have to wait for myVM to appear in the list. Try refresh   of browser.

**Comment by polichtm** [comment]
updated
