### ISSUE TITLE
Module 4: Lab 15: Azure Sentinel

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#91]
Module   4: Lab 15: Azure Sentinel
--

Ex 1   Task 1 Step 4: "click Add Azure Sentinel." should be "click   Add.". May take a while to register.
Ex 1   Task 2 Step 3: May have to scroll right to see the Configure Azure Activity   logs link.
Ex 1   Task 2 Step 7: May have to wait for data received to display. Try refresh of   browser.
Ex 1   Task 3 Step 3: May have to scroll right and scroll down to see the Create   rule option.
Ex 1   Task 4 Step 6: Select Review+create and then select Create.

**Comment by polichtm** [comment]
updated
