### ISSUE TITLE
Mod 2 Lab 9 Task 5 step 7

### ISSUE THREAD

**Issue by mjeromeleonardGH** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#92]
# Module: 02
#### Step: 07

Mod 2 Lab 9 Task 5 step 7
Description of issue

The following code is presented and appears to be expected output from the previous steps. Students are trying to execute the code from the command line and it produces an error (see attached file). 
 
deployment.apps/nginxexternal created
 service/nginxexternal created

The text should indicate more clearly the contents in the command box are not to be executed but observed from the previous instruction.

Repro steps:

1. Execute the commands above in the Bash Cloudshell
![Mod2-lab-9Ex5-step7](https://user-images.githubusercontent.com/51800630/101549281-6436b680-397b-11eb-960f-82b40810c0f0.GIF)

1.
1.

**Comment by polichtm** [comment]
As per lab instructions, you are supposed to review the output consisting of these two lines of output, not run them:

"In the Bash session within the Cloud Shell pane, **_review_** the output of the command you run in the previous task to verify that the deployment and the corresponding service have been created.

deployment.apps/nginxexternal created
service/nginxexternal created"

rgds
Marcin
