### ISSUE TITLE
Module 4: Lab 14: Azure Security Center - UI Change

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ500-AzureSecurityTechnologies#94]
Module 4: Lab 14: Azure Security Center - UI Change
--

Ex 1   Task 1 Step 10: "Use another workspace" should be "Connect   Azure VMs to a different workspace"
Ex 1   Task 1 Step 11: at end add "and when prompted, select Existing and new   VMs, and then select Apply again"

**Comment by polichtm** [comment]
updated
